### ISSUE TITLE
Set-SnipeItAsset -purchase_date

### ISSUE THREAD

**Issue by rickylewis** [snazy2000/SnipeitPS#118]
I get the following debug information when trying to set the purchase_date. I've tried a number of different date formats, but they actually error out, this one does this:

Set-Asset -Name $Asset.name -id $Asset.id -purchase_date "2020-01-23" -Verbose

VERBOSE: Performing the operation "Set-Asset" on target "ShouldProcess?".
VERBOSE: [Invoke-SnipeitMethod] Invoking method Put to URI http://localhost/api/v1/hardware/6914
VERBOSE: PUT http://localhost/api/v1/hardware/6914 with -1-byte payload
VERBOSE: [Invoke-SnipeitMethod] Failed to get an answer from the server
VERBOSE: [Invoke-SnipeitMethod] Status code: InternalServerError
VERBOSE: [Invoke-SnipeitMethod] No content was returned from.
VERBOSE: [Invoke-SnipeitMethod] Function ended

This is on a test environment, but I get exactly the result on a production environment too. Am I doing something wrong?

**Comment by PartTimeJS** [comment]
You have to set it as a -customfield

**Comment by rickylewis** [comment]
Ahhh! I did think it was something to do with customfield but i think I confused myself with -purchase_date in set-asset :)

Thanks for getting back so quickly 👍

**Comment by PetriAsi** [comment]
-purchase_date  should work also, if not, there's some bug. I'll check this closer.

**Comment by PetriAsi** [comment]
it seems that New-SnipeItAsset expect dates as  [string] when Set-SnipeItAsset expect  in [datetime] format. And I'm not sure if later works cause there's no conversion from datetime to string.

**Comment by PetriAsi** [comment]
Would it make a sense to change all date and datetime parameters to [datetime] and inside function format those  values to string for SnipeIt api. That way users don't have to know formating snipe it is using  and can operate native powershell datetimes.
 
But should get-functions return values as it (like now)  or try to format those values to native powershell datatypes like datetime?

**Comment by PetriAsi** [comment]
Fixed in v1.3
