### ISSUE TITLE
Asset name not being changed with Set-SnipeItAsset

### ISSUE THREAD

**Issue by RussellLeVasseur** [snazy2000/SnipeitPS#126]
Asset name is not being changed when running Set-SnipeItAsset.

Example:
![image](https://user-images.githubusercontent.com/58618324/119688822-52a47680-be16-11eb-9f28-7f641882c1a6.png)

**Comment by RussellLeVasseur** [comment]
@PetriAsi , so when i pass name as a customfield, it updates. It looks like this is a similar issue to purchase_date? https://github.com/snazy2000/SnipeitPS/issues/118

**Comment by PetriAsi** [comment]
thanks for reporting. Just verified this on my machine.

**Comment by PetriAsi** [comment]
It was just letter case issue. Parameter was defined in code  as "Name" and should be like "name".
It does not matter that input was writed as "name" it was always converted to "Name" .
Fix is in develop branch in few minutes.

**Comment by PetriAsi** [comment]
Fixed in v1.3
