### ISSUE TITLE
Get asset history / activity history (Get-SnipeItActivity)

### ISSUE THREAD

**Issue by rickylewis** [snazy2000/SnipeitPS#130]
Hi!

First thanks for looking into and quickly resolving the issue I raised with Set-SnipeITAsset -purchase_date.

Is there already a way to get an assets history? If not will there be a function in the future? Guessing Get-SnipeITAssetHistory or something.

Kind regards,
Ricky Lewis

**Comment by PetriAsi** [comment]
Thanks.
Yes it seems that there's api /reports/activity that will give asset history, so this can de done.
This api returning activity history for all kind of items and users so giving more general name for fuction Get-SnipeItActivity would be better.

**Comment by PetriAsi** [comment]
This is now in develop and will be published in version 1.4
