### ISSUE TITLE
Update Get-Location to Get-Locations

### ISSUE THREAD

**Issue by n-v-o** [snazy2000/SnipeitPS#14]
Related to #7 

Would it be possible to simply update this cmdlet to Get-Locations? This resolves the name conflict.

**Comment by pompushko** [comment]
`PackageManagement\Install-Package : A command with name 'Get-Location' is already available on this system. This module 'SnipeitPS' may override the existing commands. If you still want to install this module 'SnipeitPS', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage`

**Comment by snazy2000** [comment]
Im renaming this to get-locations and set-locations etc. This will be a breaking change which is why I’ve been putting it off, this will be done in next push which will be later today

**Comment by snazy2000** [comment]
Fixed in #26
