### ISSUE TITLE
Set-SnipeITLicenceSeat unfunctionnal

### ISSUE THREAD

**Issue by gvannier** [snazy2000/SnipeitPS#145]
Hello,

I'm trying to use the Set-SnipeITLicenceSeat but it is not working.
Here is the output : 

> Set-SnipeItLicenseSeat -id 5 -seat_id 410 -assigned_id 188 -Verbose
> 
> VERBOSE: Opération « Set-SnipeItLicenseSeat » en cours sur la cible « ShouldProcess? ».
> VERBOSE: [Invoke-SnipeitMethod] Invoking method Patch to URI https://snipe01.ijnext.iaas/api/v1/licenses/5/seats/410
> VERBOSE: PATCH https://snipe01.ijnext.iaas/api/v1/licenses/5/seats/410 with -1-byte payload
> VERBOSE: received -1-byte response of content type application/json
> VERBOSE: [Invoke-SnipeitMethod] Status code: 200
> VERBOSE: {"status":"success","messages":"License updated successfully.","payload":{"id":410,"license_id":5,"assigned_to":null,"notes":null,"user_id":1,"created_at":"2021-06-08 15:35:17","updated_at":"2021-06-09 07:06:40","deleted_at":null,"asset_id":null}}
> VERBOSE: [Invoke-SnipeitMethod] Function ended
> 
> 
> id          : 410
> license_id  : 5
> assigned_to :
> notes       :
> user_id     : 1
> created_at  : 2021-06-08 15:35:17
> updated_at  : 2021-06-09 07:06:40
> deleted_at  :
> asset_id    :

As you can see, the result is success but the field assigned_to is empty.
I've checked that all the ids are correct of course.

Thanks for your help.

**Comment by PetriAsi** [comment]
What version of Snipe you are running?

**Comment by gvannier** [comment]
Hello Petri,

 Version v5.1.5 - build 6029 (master)


Cordialement,

Guillaume

VANNIER

DSI

***@***.******@***.***>

M. +33 6 80 63 92 52

3, avenue du Canada ‑ Parc Technopolis ‑ bâtiment Beta

91940

Les Ulis

[https://storage.letsignit.com/5fcf5be90105a500085141b5/224603599353955309536524152569609692977.png]

[https://storage.letsignit.com/5fcf5be90105a500085141b5/241117424122630863350875084921594483851.png]<https://cloud.letsignit.com/collect/bc/600f1e88c9deee0007932022?p=Iqt_vaKNSdm0iNOMrQqtlzzIk6afYadoIfh_H4_ZCcCOKQXT-U6Y0ZOHim9EGJcI78w00mgxeCItexTljw0xXHP8sAa06ZnfYmAtjM262FA9k2IbGY2y4CsRChogtnEPEJ_vdwln_1HDDTCc0PKJiw==>

[https://storage.letsignit.com/5fcf5be90105a500085141b5/98884668582028265390935856037483513182.png]<https://cloud.letsignit.com/collect/bc/600f1e88c9deee0007932022?p=Iqt_vaKNSdm0iNOMrQqtlzzIk6afYadoIfh_H4_ZCcCOKQXT-U6Y0ZOHim9EGJcI78w00mgxeCItexTljw0xXHP8sAa06ZnfYmAtjM262FA9k2IbGY2y4CsRChogtnEPEJ_vdwln_1HDDTCc0PKJiw==>

[https://storage.letsignit.com/5fcf5be90105a500085141b5/logo_5fcf5be90105a500085141b5_7fa1342ed9ede01a9be1bbdab9a59b1c.png]<https://cloud.letsignit.com/collect/bc/600f1e88c9deee0007932022?p=Iqt_vaKNSdm0iNOMrQqtlzzIk6afYadoIfh_H4_ZCcCOKQXT-U6Y0ZOHim9EGJcI78w00mgxeCItexTljw0xXHP8sAa06ZnfYmAtjM262FAvDfjgnbBZsNq11dVsLJaurxT5OaW-c3bv9zu5BEdrLA==>

[https://storage.letsignit.com/5fcf5be90105a500085141b5/98884668582028265390935856037483513182.png]<https://cloud.letsignit.com/collect/bc/600f1e88c9deee0007932022?p=Iqt_vaKNSdm0iNOMrQqtlzzIk6afYadoIfh_H4_ZCcCOKQXT-U6Y0ZOHim9EGJcI78w00mgxeCItexTljw0xXHP8sAa06ZnfYmAtjM262FAvDfjgnbBZsNq11dVsLJaurxT5OaW-c3bv9zu5BEdrLA==>

[https://storage.letsignit.com/5fcf5be90105a500085141b5/211781871382317944355840071418513600034.png]<https://cloud.letsignit.com/collect/bc/600f1e88c9deee0007932022?p=Iqt_vaKNSdm0iNOMrQqtlzzIk6afYadoIfh_H4_ZCcCOKQXT-U6Y0ZOHim9EGJcI78w00mgxeCItexTljw0xXHP8sAa06ZnfYmAtjM262FCRJ_JBhVDI7JNZPWo8xMbxY-uDi_N7u_4_dLbc4THTsg==>

[https://storage.letsignit.com/5fcf5be90105a500085141b5/98884668582028265390935856037483513182.png]<https://cloud.letsignit.com/collect/bc/600f1e88c9deee0007932022?p=Iqt_vaKNSdm0iNOMrQqtlzzIk6afYadoIfh_H4_ZCcCOKQXT-U6Y0ZOHim9EGJcI78w00mgxeCItexTljw0xXHP8sAa06ZnfYmAtjM262FCRJ_JBhVDI7JNZPWo8xMbxY-uDi_N7u_4_dLbc4THTsg==>

[https://storage.letsignit.com/5fcf5be90105a500085141b5/154644384730201861008120789828373144777_600f237b13f9bd0045610ce5_3ff0a74c9c26da49fc3997c0aa7d9348.png]<https://cloud.letsignit.com/collect/b/600f237b13f9bd0045610ce5?p=Iqt_vaKNSdm0iNOMrQqtlzzIk6afYadoIfh_H4_ZCcCOKQXT-U6Y0ZOHim9EGJcI78w00mgxeCItexTljw0xXHP8sAa06ZnfYmAtjM262FA9rn5hNt9bkTAlOgHoUoewcXgzbluH5oDsRZQGjHJn2WgIBLTXv4fZAhra-3eqOUY_G2uEzdx6fST9DGyypzXi>

________________________________
De : Petri Asikainen ***@***.***>
Envoyé : mercredi 9 juin 2021 14:29
À : snazy2000/SnipeitPS ***@***.***>
Cc : Guillaume VANNIER ***@***.***>; Author ***@***.***>
Objet : Re: [snazy2000/SnipeitPS] Set-SnipeITLicenceSeat unfunctionnal (#145)


What version of Snipe you are running?

**Comment by PetriAsi** [comment]
Found it, I have mixed assigend_id and assigned_to. Already made PR to fix this #146

**Comment by PetriAsi** [comment]
This is fixed in develop. Making new release while writing this.

**Comment by gvannier** [comment]
Great, it's working fine now.

Thank you

**Comment by PetriAsi** [comment]
Great! It was easy to fix with your verbose log :)
