### ISSUE TITLE
New-SnipeItAccessory and Set-SnipeItAccessoryOwner

### ISSUE THREAD

**Issue by LC-cchristiansen** [snazy2000/SnipeitPS#15]
Would love if there was a New-Accessory command as well as the accompanied Set-AccessoryOwner like there are for assets.

The built in Web Importer for snipe-it doesn't allow for checking accessories out to users, but I may be able to write a powershell script to iterate through a CSV if this functionality existed in SnipeitPS.

**Comment by snazy2000** [comment]
#24 Ive added new and set accessory, its not currently possible via the api to set the owner by looks of it

**Comment by PetriAsi** [comment]
Now there api to checkout accessory to user

**Comment by PetriAsi** [comment]
Fixed in v1.3
