### ISSUE TITLE
Get-User Search Breaks With Plus Sign

### ISSUE THREAD

**Issue by rpesta** [snazy2000/SnipeitPS#16]
Get-User -search "email+label@email.com" appears to not work at all, as it doesn't return any results when the email address exists in the system. I think the + sign is breaking the search.

Here's the verbose output:
VERBOSE: [ConvertTo-GetParameter] Making HTTP get parameter string out of a hashtable
VERBOSE: [Invoke-SnipeitMethod] Invoking method Get to URI https://domain.snipe-it.io/api/v1/users?offset=0&search=test+2@test.com&sort=&limit=50&order=desc
VERBOSE: GET https://domain.snipe-it.io/api/v1/users?offset=0&search=test+2@test.com&sort=&limit=50&order=desc with 0-byte payload
VERBOSE: received -1-byte response of content type application/json
VERBOSE: [Invoke-SnipeitMethod] Status code: 200
VERBOSE: {"total":0,"rows":[]}
VERBOSE: [Invoke-SnipeitMethod] Function ended

**Comment by shinjijai** [comment]
I haven't tested it, but if you update Invoke-SnipeITMethod's URI to have `[System.Web.HttpUtility]::UrlEncode($URI)` this should fix the issue.
