### ISSUE TITLE
Checking License Seat Back in

### ISSUE THREAD

**Issue by Christopheric1** [snazy2000/SnipeitPS#167]
I have not found a way to check a license seat back in. I can remove the "assigned_user" and make it $null, but it doesn't change that it is still "checkout out" from the API. It shows from the GUI that you can check it back out, but the count doesn't change of open seats. Any help on this would be amazing.

**Comment by PetriAsi** [comment]
Licenseseat  PR code  is here https://github.com/snipe/snipe-it/pull/8058/files
I did just quick look at it.  it seems that to checkin license both values assigned_to and asset_id have to set to null (or empty)

Could you post you powershell codes with -Verbose output

**Comment by Christopheric1** [comment]
Here is my code:

` do {
     cls
      $LicIDs =  (Get-SnipeITLicense -All)
  If($LicIDs.Count -gt 1){
  $IDB = 0
  $result3 = $(foreach ($item3 in $LicIDs){
  $item3 | select @{l='IDB';e={$IDB}},Name,seats,free_seats_count
  $IDB++}) |
  Out-GridView -Title 'Select the License You Want to Check In' -OutputMode Single |
foreach { $LicIDs[$_.IDB] }

$LicID = $result3.id
$LicCount = $result3.free_seats_count
$LicT = $result3.seats
  }

     else {
  $LicID = $LicIDs.id
  $LicCount = $result3.free_seats_count
  $LicT = $result3.seats
  } 
     If($LicCount -eq $LicT) {
  Write-host -ForegroundColor Red "All Licenses are already checked in"   
  Start-Sleep 2  
     }    
    
 }until ($LicCount -ne $LicT)

  $LicSeatNames =  (Get-SnipeITLicenseSeat -id $LicID)
  If($LicSeatNames.Count -gt 1){
  $IDC = 0
  $result4 = $(foreach ($item3 in $LicSeatNames){
  $item3 | select @{l='IDC';e={$IDC}},ID,assigned_user
  $IDC++}) |
  Out-GridView -Title 'Select the License You Want to Check In' -OutputMode Single |
foreach { $LicSeatNames[$_.IDC] }

$seatID = $result4.id

  }
 

 Set-SnipeItLicenseSeat -id $LicID -seat_id $seatid -assigned_to $null -asset_id $null -verbose

 Write-Host License for $result3.name has been removed for $userprofile.name`


Here is the output:
`VERBOSE: Performing the operation "Set-SnipeitLicenseSeat" on target "ShouldProcess?".
VERBOSE: [Invoke-SnipeitMethod] Invoking method Patch to URI http://snipe-it1.local/api/v1/licenses/6/seats/21
VERBOSE: PATCH http://snipe-it1.local/api/v1/licenses/6/seats/21 with -1-byte payload
VERBOSE: [Invoke-SnipeitMethod] Failed to get an answer from the server
VERBOSE: [Invoke-SnipeitMethod] Status code: InternalServerError
VERBOSE: [Invoke-SnipeitMethod] No content was returned from.
VERBOSE: [Invoke-SnipeitMethod] Function ended
License for Adobe Acrobat 2017 Pro has been removed for User
`

**Comment by PetriAsi** [comment]
Thanks. Looks fine. Please test this also -Debug switch. 
When I tried this with -debug switch on my system and $null values were converted to zeros. 
```json
DEBUG: {
  "seat_id": 6,
  "assigned_to": 0,
  "asset_id": 0
}
```
So this is could be  get-parametervalue issue, it should translate $null values parameters to null, not  zeros.

**Comment by PetriAsi** [comment]
It's parameter type issue instead.  have to use parameter type  [Nullable[System.Int32]] currently [int] for assigned_to and asset_id.

**Comment by PetriAsi** [comment]
Fixed in v1.7.159

**Comment by stevenbaron86** [comment]
Hey thanks for this. I'd like to send you a piece of swag from our   @@company. How can I get ahold of you without publicly announcing either of our personal contact info? @PetriAsi

**Comment by Christopheric1** [comment]
> Hey thanks for this. I'd like to send you a piece of swag from our company. How can I get ahold of you without publicly announcing either of our personal contact info? @PetriAsi

Are you talking about PetriAsi? or me? I imagine you are talking about him as he has done some amazing work.

**Comment by PetriAsi** [comment]
Nice! 
@stevenbaron86 Send me a email and  I'll send my contact info to you.

**Comment by stevenbaron86** [comment]
Ah hey where did that other comment go! hit my work email
***@***.*** with a shipping address :)

**Comment by stevenbaron86** [comment]
I suck at github today
