### ISSUE TITLE
Unable to assigned Asset to user

### ISSUE THREAD

**Issue by gvannier** [snazy2000/SnipeitPS#173]
Hello,

I'm unable to assigned a user to an asset.
The asset is unavailable after the opération
![Screenshot - 16_06_2021 , 11_15_03](https://user-images.githubusercontent.com/85609044/122193055-78142580-ce94-11eb-8ce1-71f04a0cf4f4.png)
![Screenshot - 16_06_2021 , 11_07_34](https://user-images.githubusercontent.com/85609044/122193058-78acbc00-ce94-11eb-8919-c82b1ccff490.png)
![Screenshot - 16_06_2021 , 11_08_16](https://user-images.githubusercontent.com/85609044/122193059-78acbc00-ce94-11eb-919d-fb63e700e5a3.png)
![Screenshot - 16_06_2021 , 11_10_13](https://user-images.githubusercontent.com/85609044/122193062-79455280-ce94-11eb-916b-aa048cef902b.png)

Thanks for your help

**Comment by PetriAsi** [comment]
Please use Set-SnipeitAssetOwner function to checkout assets.
