### ISSUE TITLE
Get-SnipeITAsset -serial returns all the assets

### ISSUE THREAD

**Issue by gvannier** [snazy2000/SnipeitPS#174]
Hello,

Another small bug.
If i search an Asset using Get-SnipeITAsset -search <string>, all the assets are returned.
![image](https://user-images.githubusercontent.com/85609044/122197015-11910680-ce98-11eb-8028-7f6960dbce83.png)

Maybe it is because of the syntax of the phonenumber.

**Comment by PetriAsi** [comment]
It should work with all kind of strings. There was an other bug when using  "get-snipeitasset -serial" please try a just released version v1.7.162.

**Comment by PetriAsi** [comment]
@gvannier I'll close this, but if you still have issues when using latest version of SnipeitPS , please reopen this.
