### ISSUE TITLE
Set-SnipeITComponent Options

### ISSUE THREAD

**Issue by Christopheric1** [snazy2000/SnipeitPS#178]
I have been trying to figure out a way to Checkout a Component through the PS API and have been unable to figure it out. When I do the ```Get-Help Set-SnipeItComponent -Full```, these are the only options I get. Am I choosing the wrong one?
```
    -id <Int32[]>
    -qty <Int32>
    -min_amt <Int32>
    -name <String>
    -company_id <Int32>
    -location_id <Int32>
    -order_number <String>
    -purchase_date <DateTime>
    -purchase_cost <Single>
```

Thanks!

**Comment by PetriAsi** [comment]
Sorry currently there's [no documented official api for checkout/in components](https://snipe-it.readme.io/reference#componentsidassets). That something that could be done using same
endpoint that snipe it webgui is using. Html form is using path /components/[id]/checkout
There's [issue on snipe it, it better to keep it active to get this implemented](https://github.com/snipe/snipe-it/issues/6935).

**Comment by Christopheric1** [comment]
Okay, thanks. I will close this.
