### ISSUE TITLE
Set-SnipeitAccessory Issue, cannot set min_amt

### ISSUE THREAD

**Issue by Christopheric1** [snazy2000/SnipeitPS#181]
When trying to use the ```Set-SnipeITAccessory -id $monid -min_amt 2 -debug```, I get the following error from PS:
```
Set-SnipeitAccessory : A parameter cannot be found that matches parameter name 'min_amt'. This error might have been caused by applying the default parameter binding. You can disable the default parameter binding in $PSDefaultParameterValues by setting 
$PSDefaultParameterValues["Disabled"] to be $true, and then trying again. The following default parameters were successfully bound for this cmdlet when the error occurred: -url -apiKey
At line:1 char:1
+ Set-SnipeitAccessory -id $monid -min_amt 2 -debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SnipeitAccessory], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-SnipeitAccessory
```
Yet when I check if it is something you can use, it comes up as an option, but it is ```-min_qty``` and that doesn't match what is in the output:

```
id              : 3
name            : P2419H
category_id     : 5
user_id         : 
qty             : 2
requestable     : False
created_at      : 2021-06-16 11:01:48
updated_at      : 2021-06-16 11:01:48
deleted_at      : 
location_id     : 2
purchase_date   : 
purchase_cost   : 
order_number    : 
company_id      : 1
min_amt         : 
manufacturer_id : 4
model_number    : 
image           : 
supplier_id     : 
```

Let me know if there is something I am missing.

Thanks!

**Comment by PetriAsi** [comment]
Could it be that you are using old  version of SnipePS? -min_amt
Get-module  snipeitps
will tell what version you have installen on your system.

Update-module snipeitps
Will update module to latest. 

After update you have reload module. 

Remove-module snipeitps
Import-module SnipeitPS

**Comment by Christopheric1** [comment]
I ended up reloading and it showed up. Thanks!

**Comment by Christopheric1** [comment]
Nvm, I thought this was on a different topic. I am on the latest version:

```
ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                                     
---------- -------    ----                                ----------------                                                                                                                                                                                                     
Script     1.7.159    SnipeitPS    
```

**Comment by Christopheric1** [comment]
![snipeit](https://user-images.githubusercontent.com/39960760/122275989-2fab3680-ce99-11eb-8093-fb4f74ea9e00.png)

**Comment by PetriAsi** [comment]
Just saw same, new-snipeitaccessory and set-snipeitassessory both use different parameter names. Tested both and either of them doesn't seem to write anything to Snipe It. Have to look at this closer.

**Comment by PetriAsi** [comment]
This is snipe it issue. Just made Snipe it [PR 9717 to fix this](https://github.com/snipe/snipe-it/pull/9717).

**Comment by PetriAsi** [comment]
As snipe/snipe-it#9717 is merged I'll close this now and after next snipe it is out this is fixed.
