### ISSUE TITLE
Set-SnipeItAccessory

### ISSUE THREAD

**Issue by Christopheric1** [snazy2000/SnipeitPS#182]
I was curious if the option could be added for ```-model_number``` could be added to ```Set-SnipeItAccessory``` and also ```New-SnipeItAccessory```? I saw it listed on the site for the API [here](https://snipe-it.readme.io/reference#accessories)

Thanks again for all of your help!

**Comment by PetriAsi** [comment]
-model_number  is released in v.1.8.x
