### ISSUE TITLE
How do you search for licenses assigned to a user?

### ISSUE THREAD

**Issue by stevenbaron86** [snazy2000/SnipeitPS#183]
## Context
Offboarding script, hoping to report out to purchasing which licenses are being free'd up

## Your Environment

* SnipitPS Module version used: 1.7.162
* Operating System and PowerShell version: W10 21H1, PSversion 5.1.19041.906
* Snipe It version: v5.1.4 build 5886

## Expected Behavior
I guess get-snipeituser returning associated licenses. 

## Current Behavior

My current ugly approach is:

$snipeituser = get-snipeituser {user being offboarded}
$licenses = Get-SnipeitLicense
foreach( $license in $licenses ) {
    $licenseSeat += Get-SnipeitLicenseSeat -id $license.id 
    if ($licenseSeat.assigned_user.name -eq "$snipeituser.name") {
        $result += $licenseseat
    } 
}

## Possible Solution
Maybe I am going around this wrong. In the UI, the user page has a licenses tab which would be awesome to nab. Am I just missing something?

Return assigned licenses in get-snipeituser
Could get-snipeitlicense return its respective snipeitlicenseseats?

## Steps to Reproduce (for bugs)

Thanks for the help!

**Comment by PetriAsi** [comment]
Currently SnipeitPS  don't have this feature. There api for this (https://snipe-it.readme.io/reference#usersidlicenses)
and same kind of api for assets also.
As api is returning licenses (not seats) , would it make sense to implement this as parameter for get-snipeitLicense  by using parameters like  -user_id and -asset_id?

**Comment by stevenbaron86** [comment]
That would totally work for my case. One less step for my use case would be to have your mentioned parameter in get-snipeituser. Im getting by right now either way but shorter code is cleaner code. Thanks for sharing the module yall

**Comment by PetriAsi** [comment]
This is now in develop. I also wrote support for  other similar api endpoints. So you can now search asset with specific component etc...
Released in v.1.8.x

**Comment by PetriAsi** [comment]
So try: 
Get-SnipeitLicense -user_id
To get licenses assigned to specific user

**Comment by stevenbaron86** [comment]
Thought I commented but it disappeared. @PetriAsi drop me a line @ steven.baron@probablymonsters.com and ill ship you some swag in appreciation for your help. Lets delete this comment after you've got the email addy so folks dont scrape it for nefarious reasons.
