### ISSUE TITLE
Checkin License

### ISSUE THREAD

**Issue by stevenbaron86** [snazy2000/SnipeitPS#184]
## Context
Hey thanks yall another issue... I cant seem to find a way to check-in a license.

## Your Environment
SnipitPS Module version used: 1.7.162
Operating System and PowerShell version: W10 21H1, PSversion 5.1.19041.906
Snipe It version: v5.1.4 build 5886

## Expected Behavior
`(get-snipeitlicenseseat -id $id).available_actions` teases me with checkin and checkout
`set-snipeitlicenseseat -id $id -seat_id $seatid` would be awesome if it had the ability to check in.

## Current Behavior
I cant find a way to automate software checkins. I'm like | | this close to not ever having to log into the UI :)

## Possible Solution
`set-snipeitlicenseseat -id $id -seat_id $seatid -action checkin` or some other parameter to allow checkins

## Steps to Reproduce (for bugs)

Thank you again!

**Comment by PetriAsi** [comment]
Those available_actions are referencing to snipe it app actions, not actions available in SnipeitPS.

There's  issue #167, try to set both   -asset_id and -assigned_id to $null, like
```powershell
Set-SnipeitLicenceSeat -ID 1 -seat_id 1 -asset_id $null -assigned_id $null
```
I'll add example for this , it will be next release
```powershell
get-help Set-SnipeitLicence -full
```
