### ISSUE TITLE
Question regarding TLS version specifications

### ISSUE THREAD

**Issue by snipe** [snazy2000/SnipeitPS#203]
Hi @snazy2000 and @PetriAsi :) Happy monday - I hope you're both keeping well. I have a quick question that I'm hoping someone can answer for me, as I'm not as good at Powershell as I used to be.

We're in the process of disabling TLS 1.0 and 1.1 on hosted servers where no one is currently using those versions (and warning customers who are using that support will be discontinued soon). We do still see some 1.0 requests, largely from Powershell users, and I was wondering if this or a previous version of SnipeitPS specified TLS 1.0, like maybe these customers are using an old version of SnipeitPS, and we can advise them to upgrade or something. (Ideally, any script would skip specifying a version and would instead just let accept whatever the latest is, but I'm not sure if older versions of SnipeitPS may have been more specific.)

If SnipeitPS has never specified a TLS version, it's possible that what we're seeing are just home-grown Powershell scripts that are doing the specification, but I figured it was worth reaching out and asking :)

**Comment by PetriAsi** [comment]
@snipe Hi, it's already Tuesday over here, when I read this, happy tuesday. :)
Powershell is using by default TLS protocol that .net  is using and .net is using system default. Iäm not sure but assume that those 1.0 connections are 
coming from older installations, perhaps from older powershell 3.0. Current on box powershell for windows 10 is 5.1 and powershell 7 can be installed on side. And also on other platforms.
SnipeitPS does not specify any TLS levels.  To force powershell select TLS version 1.2 following can be added to start of script / session:
```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```
Or change systems default TLS vie registy or group policy   but that's another story.

**Comment by PetriAsi** [comment]
@snipe here's that other story, set .net default TLS level system wide :) 
[From "Solving the TLS 1.0 Problem, 2nd Edition"](https://docs.microsoft.com/en-us/security/engineering/solving-tls1-problem)
```powershell
#Add a system-wide registry key (e.g. via group policy) to any machine that needs to make TLS 1.2 connections from 
#a .NET app. This will cause .NET to use the "System Default" TLS versions which adds TLS 1.2 as an available protocol 
# AND it will allow the scripts to use future TLS Versions when the OS supports them. (e.g. TLS 1.3)  

    reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:64

    reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:32
```

**Comment by MrMontesa** [comment]
Hey,
just want to add one thing as I experienced issues with disablement of TLS 1.0 and 1.1 while using another web service:

Even though you can force Powershell to use TLS 1.2 you cannot add new ciphers, which is a problem. We're still using Win Server 2012 R2 for our scripts. Those do NOT have the most recent and common ciphers, so the scripts cannot connect to the REST API even though Net.SecurityProtocolType is set to Tls12.
Some more details here: https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-8-1
Best Sebastian

**Comment by PetriAsi** [comment]
@MrMontesa Thanks! good point, compatible ciphers are also needed. 
I just tested with 2012 r2 server , upgraded it's powershell to 5.1 (to run latest version of SnipeitPS)  and TLS1.2 seems to work nicely with  Snipe it saas-service.

**Comment by snipe** [comment]
Thank you both so much for your quick responses and thoughtful replies. I haven’t worked on windows in literally nearly 15 years, so I’m a little rusty these days, but everything you’re saying makes perfect sense. This gives me a lot to work with, so thank you! <3

Happy…. Twednesday ? 😬 (I’m west coast US, so…)

**Comment by snipe** [comment]
@MrMontesa just wanted to add in an extra <3 for you - that info will definitely be helpful moving forward. Thank you so much

Love,
A Linux nerd 😁
