### ISSUE TITLE
Error when Importing Module

### ISSUE THREAD

**Issue by RussellLeVasseur** [snazy2000/SnipeitPS#205]
## Context

Module will not load. Throws an error. 
```
Set-SnipeitAlias : The term 'Set-SnipeitAlias' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.9.176\SnipeitPS.psm1:18 char:1
+ Set-SnipeitAlias
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-SnipeitAlias:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

```
PS C:\> get-module -name SnipeitPS

ModuleType Version    Name                                ExportedCommands                                       
---------- -------    ----                                ----------------                                       
Script     1.9.176    SnipeitPS  
```

I've tried uninstalled and reinstalling the module. Purging, Restarting, etc. Running Powershell ISE as Admin. 

This is the full printout when running `Import-Module -Name SnipeitPS`:
```
PS C:\> Import-Module -Name SnipeitPS -Verbose -Force;
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.9.176\SnipeitPS.psd1'.
VERBOSE: Removing the imported "Get-SnipeitAccessory" function.
VERBOSE: Removing the imported "Get-SnipeitAccessoryOwner" function.
VERBOSE: Removing the imported "Get-SnipeitActivity" function.
VERBOSE: Removing the imported "Get-SnipeitAsset" function.
VERBOSE: Removing the imported "Get-SnipeitAssetMaintenance" function.
VERBOSE: Removing the imported "Get-SnipeitCategory" function.
VERBOSE: Removing the imported "Get-SnipeitCompany" function.
VERBOSE: Removing the imported "Get-SnipeitComponent" function.
VERBOSE: Removing the imported "Get-SnipeitConsumable" function.
VERBOSE: Removing the imported "Get-SnipeitCustomField" function.
VERBOSE: Removing the imported "Get-SnipeitDepartment" function.
VERBOSE: Removing the imported "Get-SnipeitFieldset" function.
VERBOSE: Removing the imported "Get-SnipeitLicense" function.
VERBOSE: Removing the imported "Get-SnipeitLicenseSeat" function.
VERBOSE: Removing the imported "Get-SnipeitLocation" function.
VERBOSE: Removing the imported "Get-SnipeitManufacturer" function.
VERBOSE: Removing the imported "Get-SnipeitModel" function.
VERBOSE: Removing the imported "Get-SnipeitStatus" function.
VERBOSE: Removing the imported "Get-SnipeitSupplier" function.
VERBOSE: Removing the imported "Get-SnipeitUser" function.
VERBOSE: Removing the imported "New-SnipeitAccessory" function.
VERBOSE: Removing the imported "New-SnipeitAsset" function.
VERBOSE: Removing the imported "New-SnipeitAssetMaintenance" function.
VERBOSE: Removing the imported "New-SnipeitAudit" function.
VERBOSE: Removing the imported "New-SnipeitCategory" function.
VERBOSE: Removing the imported "New-SnipeitCompany" function.
VERBOSE: Removing the imported "New-SnipeitComponent" function.
VERBOSE: Removing the imported "New-SnipeitConsumable" function.
VERBOSE: Removing the imported "New-SnipeitCustomField" function.
VERBOSE: Removing the imported "New-SnipeitDepartment" function.
VERBOSE: Removing the imported "New-SnipeitLicense" function.
VERBOSE: Removing the imported "New-SnipeitLocation" function.
VERBOSE: Removing the imported "New-SnipeitManufacturer" function.
VERBOSE: Removing the imported "New-SnipeitModel" function.
VERBOSE: Removing the imported "New-SnipeitSupplier" function.
VERBOSE: Removing the imported "New-SnipeitUser" function.
VERBOSE: Removing the imported "Remove-SnipeitAccessory" function.
VERBOSE: Removing the imported "Remove-SnipeitAsset" function.
VERBOSE: Removing the imported "Remove-SnipeitAssetMaintenance" function.
VERBOSE: Removing the imported "Remove-SnipeitCategory" function.
VERBOSE: Removing the imported "Remove-SnipeitCompany" function.
VERBOSE: Removing the imported "Remove-SnipeitComponent" function.
VERBOSE: Removing the imported "Remove-SnipeitConsumable" function.
VERBOSE: Removing the imported "Remove-SnipeitCustomField" function.
VERBOSE: Removing the imported "Remove-SnipeitDepartment" function.
VERBOSE: Removing the imported "Remove-SnipeitLicense" function.
VERBOSE: Removing the imported "Remove-SnipeitLocation" function.
VERBOSE: Removing the imported "Remove-SnipeitManufacturer" function.
VERBOSE: Removing the imported "Remove-SnipeitModel" function.
VERBOSE: Removing the imported "Remove-SnipeitSupplier" function.
VERBOSE: Removing the imported "Remove-SnipeitUser" function.
VERBOSE: Removing the imported "Reset-SnipeitAccessoryOwner" function.
VERBOSE: Removing the imported "Reset-SnipeitAssetOwner" function.
VERBOSE: Removing the imported "Set-SnipeitAccessory" function.
VERBOSE: Removing the imported "Set-SnipeitAccessoryOwner" function.
VERBOSE: Removing the imported "Set-SnipeitAsset" function.
VERBOSE: Removing the imported "Set-SnipeitAssetOwner" function.
VERBOSE: Removing the imported "Set-SnipeitCategory" function.
VERBOSE: Removing the imported "Set-SnipeitCompany" function.
VERBOSE: Removing the imported "Set-SnipeitComponent" function.
VERBOSE: Removing the imported "Set-SnipeitConsumable" function.
VERBOSE: Removing the imported "Set-SnipeitCustomField" function.
VERBOSE: Removing the imported "Set-SnipeitDepartment" function.
VERBOSE: Removing the imported "Set-SnipeitInfo" function.
VERBOSE: Removing the imported "Set-SnipeitLicense" function.
VERBOSE: Removing the imported "Set-SnipeitLicenseSeat" function.
VERBOSE: Removing the imported "Set-SnipeitLocation" function.
VERBOSE: Removing the imported "Set-SnipeitManufacturer" function.
VERBOSE: Removing the imported "Set-SnipeitModel" function.
VERBOSE: Removing the imported "Set-SnipeitStatus" function.
VERBOSE: Removing the imported "Set-SnipeitSupplier" function.
VERBOSE: Removing the imported "Set-SnipeitUser" function.
VERBOSE: Removing the imported "Update-SnipeitAlias" function.
VERBOSE: Removing the imported "Get-Accessory" alias.
VERBOSE: Removing the imported "Get-Asset" alias.
VERBOSE: Removing the imported "Get-AssetMaintenance" alias.
VERBOSE: Removing the imported "Get-Category" alias.
VERBOSE: Removing the imported "Get-Company" alias.
VERBOSE: Removing the imported "Get-Component" alias.
VERBOSE: Removing the imported "Get-CustomField" alias.
VERBOSE: Removing the imported "Get-Department" alias.
VERBOSE: Removing the imported "Get-Fieldset" alias.
VERBOSE: Removing the imported "Get-Manufacturer" alias.
VERBOSE: Removing the imported "Get-Model" alias.
VERBOSE: Removing the imported "Get-Status" alias.
VERBOSE: Removing the imported "Get-Supplier" alias.
VERBOSE: Removing the imported "Get-User" alias.
VERBOSE: Removing the imported "New-Accessory" alias.
VERBOSE: Removing the imported "New-Asset" alias.
VERBOSE: Removing the imported "New-AssetMaintenance" alias.
VERBOSE: Removing the imported "New-Category" alias.
VERBOSE: Removing the imported "New-Component" alias.
VERBOSE: Removing the imported "New-CustomField" alias.
VERBOSE: Removing the imported "New-Department" alias.
VERBOSE: Removing the imported "New-License" alias.
VERBOSE: Removing the imported "New-Location" alias.
VERBOSE: Removing the imported "New-Manufacturer" alias.
VERBOSE: Removing the imported "New-Model" alias.
VERBOSE: Removing the imported "New-User" alias.
VERBOSE: Removing the imported "Remove-Asset" alias.
VERBOSE: Removing the imported "Remove-User" alias.
VERBOSE: Removing the imported "Set-Accessory" alias.
VERBOSE: Removing the imported "Set-Asset" alias.
VERBOSE: Removing the imported "Set-AssetOwner" alias.
VERBOSE: Removing the imported "Set-Component" alias.
VERBOSE: Removing the imported "Set-Info" alias.
VERBOSE: Removing the imported "Set-License" alias.
VERBOSE: Removing the imported "Set-Model" alias.
VERBOSE: Removing the imported "Set-User" alias.
VERBOSE: Populating RepositorySourceLocation property for module SnipeitPS.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.9.176\SnipeitPS.psm1'.
Set-SnipeitAlias : The term 'Set-SnipeitAlias' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.9.176\SnipeitPS.psm1:18 char:1
+ Set-SnipeitAlias
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-SnipeitAlias:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

PS C:\>
```

**Comment by RussellLeVasseur** [comment]
Might be time to deprecate the Aliases completely?

**Comment by PetriAsi** [comment]
H, what platform / powershell version you are running?
 Can't reproduce this on my Windows 10 machine.I imported module without any issues to  powershell 5.1 and powershell 7 .

**Comment by RussellLeVasseur** [comment]
> 
> 
> H, what platform / powershell version you are running?
> Can't reproduce this on my Windows 10 machine. I imported module without any issues to powershell 5.1 and powershell 7 . And also linux loads module just fine to pwsh 7 core.

This is occuring across many of my office workstations causing my scripts using SnipeItPs to fail. All on this same version.
![image](https://user-images.githubusercontent.com/58618324/128547737-d2470d02-c979-4882-8a4f-ef88a70e7193.png)

**Comment by RussellLeVasseur** [comment]
It seems to work fine in an Admin powershell window, but the issue occurs when being ran in PowershellISE as admin after you import it once, or when you are running a compiled ps1 as an exe with the System account.

**Comment by PetriAsi** [comment]
Have you installed module global or currentuser scope?

**Comment by RussellLeVasseur** [comment]
> Have you installed module global or currentuser scope? 

Default install is global, correct? 
I'll check the $Env:PSModulePath Monday, but that should be good.

**Comment by PetriAsi** [comment]
Yes default is global. It should work from any scope. Is anything else changed? New security settings for workstations or something like that. Reason Im asking that is that I spent lot of time Last week with strange issues after enabled some attack surface redution rules with intune endpoint management. IssuesI havr did not were snipeitps related, but some config changes could effect snipeit also. Module code is not currently signed, so forcing script signing will give some issues.

**Comment by RussellLeVasseur** [comment]
> Yes default is global. It should work from any scope. Is anything else changed? New security settings for workstations or something like that. Reason Im asking that is that I spent lot of time Last week with strange issues after enabled some attack surface redution rules with intune endpoint management. IssuesI havr did not were snipeitps related, but some config changes could effect snipeit also. Module code is not currently signed, so forcing script signing will give some issues.

I'm always implementing new security for vulnerabilities and things as they come up, but I don't think anything should've changed that would affect powershell. My powershell execution policy is still unrestricted at this time across the domain. I'm in the process of doing some script signing and possibly setting it to allsigned in the near future but not right now. I was googling a lot this week prior to opening this issue and couldn't find anything that solved the issue. I'll keep trying next week and keep this open for a bit, if I find a solution I would like to add it here for future knowledge for others.

**Comment by PetriAsi** [comment]
Nice, thanks to keep us posted. I think  that for longer run we really need code signing for SnipeitPS. @snazy2000 do you have active certificate to setup with appveyor / ps gallery toolchain?

**Comment by PetriAsi** [comment]
@RussellLeVasseur  Just googled your build version "10.0.22000.65" and powershell version 5.1.22000.65 All result are referencing to Windows 11 (insider preview)?

**Comment by RussellLeVasseur** [comment]
> @RussellLeVasseur  Just googled your build version "10.0.22000.65" and powershell version 5.1.22000.65 All result are referencing to Windows 11 (insider preview)?

On my workstation yes, but my other 80 workstations are Windows 10 21H1

**Comment by PetriAsi** [comment]
Lets test more some basics things. Is some files really missing? Try to run following and compare to output from my system.

```powershell
#count of snipeit modules
Get-InstalledModule snipeitps  | measure
Count    : 1

#module file count
get-childitem (Get-InstalledModule snipeitps -MaximumVersion 1.9.176).installedLocation -Recurse | measure

Count    : 89

#Is Set-SnipeitAlias there?
Test-Path  (Join-path -Path ( Get-InstalledModule snipeitps -MaximumVersion 1.9.176).installedLocation -ChildPath Private/Set-Snipeitalias.ps1)
True

```
And some things that  noticed from your orginal issue:
You provided output of "Get-Module SnipeitPS" . As it shows output, module in loaded. 


Actually that did it! Reproduced error. Tried to reload module with:
```pwsh
import-module snipeitps -Force
Set-SnipeitAlias : The term 'Set-SnipeitAlias' is not recognized as the name of a cmdlet, function, script file, or ope
rable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again
``` 
But only when  module is already loaded. First import with force is working.  I usually "force" reload of module by running "Remove-module SnipeitPS ; Import-Module SnipeitPS" Is there some reason why you are forcing reload of module? 

Right now I have no idea why -forcing module import gives that kind of error, but maybe you can adjust your scripts and do module reimport after you have removed first instance of module.

**Comment by RussellLeVasseur** [comment]
> 
> 
> Lets test more some basics things. Is some files really missing? Try to run following and compare to output from my system.
> 
> ```powershell
> #count of snipeit modules
> Get-InstalledModule snipeitps  | measure
> Count    : 1
> 
> #module file count
> get-childitem (Get-InstalledModule snipeitps -MaximumVersion 1.9.176).installedLocation -Recurse | measure
> 
> Count    : 89
> 
> #Is Set-SnipeitAlias there?
> Test-Path  (Join-path -Path ( Get-InstalledModule snipeitps -MaximumVersion 1.9.176).installedLocation -ChildPath Private/Set-Snipeitalias.ps1)
> True
> ```
> 
> And some things that noticed from your orginal issue:
> You provided output of "Get-Module SnipeitPS" . As it shows output, module in loaded.
> 
> Yes! **I finaly reproduced error**. Tried to reload module with:
> 
> ```powershell
> import-module snipeitps -Force
> Set-SnipeitAlias : The term 'Set-SnipeitAlias' is not recognized as the name of a cmdlet, function, script file, or ope
> rable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again
> ```
> 
> **But only when module is already loaded**. Also first import with force is working. I usually "force" reload of module by running "**Remove-module SnipeitPS ; Import-Module SnipeitPS**". **It always runs without error**s. Is there some reason why you are trying forcing reload of module?
> 
> Right now I have no idea why -forcing module import gives that kind of error, but maybe you can adjust your scripts and do module reimport after you have removed first instance of module.

Ok, so it looks like I am seeing similar things to your commands:
![image](https://user-images.githubusercontent.com/58618324/129056013-ca7f3d14-08dd-43ab-9040-5b6e360f0243.png)

When doing Get-Command -Module SnipeitPS i get this:
![image](https://user-images.githubusercontent.com/58618324/129056108-7bdbd04a-f3da-46a6-a9de-1e6ddd224d72.png)

I am not seeing any of the new Get- or New- Commands, only legacy ones?

**Comment by RussellLeVasseur** [comment]
So doing `Remove-Module -Name SnipeitPS` then re-importing it, now shows all of the commands. Is this just a stupid bug with powershell more than likely?

**Comment by PetriAsi** [comment]
Could be bug or feature who knows :)   I tried to  reproduce this with couple of other modules, but got no errors. But if everything is working for you now , could I close this issue now?

**Comment by PetriAsi** [comment]
I close this issue now, feel free to reopen it, if needed.
