### ISSUE TITLE
Set-SnipeitUser -id ## -username not working

### ISSUE THREAD

**Issue by yaroz** [snazy2000/SnipeitPS#213]
## Context
Trying to reset usernames for all of the people in Snipe-IT, to conform to the same standard.  

## Your Environment

* SnipitPS Module version used: 1.9.181
* Operating System and PowerShell version: Win10, 2021.8.0 (using VS Code)
* Snipe It version: 4.9.4

## Expected Behavior
It should change the username for the user

## Current Behavior
I grabbed a list of all of the users, using get-snipeitusers, and do a foreach ($su in $snipeusers) {set-snipeituser -id $su.id -username $su.employee_num}.  It does not change the username.

Output of one user:
DEBUG: [Invoke-SnipeitMethod] Invoke-WebRequest with:
Name                           Value
----                           -----
ErrorAction                    SilentlyContinue
UseBasicParsing                True
Body                           {…
Method                         PATCH
Headers                        {Content-Type, Authorization, Accept}
Uri                            http://it.teamelmers.com/snipe-it/api/v1/users/387

DEBUG: [Invoke-SnipeitMethod] Executed WebRequest. Access @{status=success; messages=User was successfully updated.; payload=} to see details
id                   : 387
avatar               : //gravatar.com/avatar/14957973d383ded86f7323ab6a634b15
name                 : Joe User
first_name           : Joe
last_name            : User
username             : juser@company.com
employee_num         : 2216
manager              : 
jobtitle             : Driver-Trains
phone                : 
website              : 
address              : 
city                 : 
state                : 
country              : 
zip                  : 
email                : juser@company.com
department           : @{id=2; name=Trucking}
location             : @{id=3; name=TC}
notes                : 
permissions          : 
activated            : False
two_factor_activated : False
two_factor_enrolled  : False
assets_count         : 0
licenses_count       : 0
accessories_count    : 0
consumables_count    : 0
company              : 
created_at           : @{datetime=2020-08-21 15:36:01; formatted=2020-08-21 03:36 PM}
updated_at           : @{datetime=2021-03-12 08:41:00; formatted=2021-03-12 08:41 AM}
last_login           : 
available_actions    : @{update=True; delete=True; clone=True; restore=False}
groups               : 

Confirm
Are you sure you want to perform this action?
Performing the operation "Set-SnipeitUser" on target "ShouldProcess?".
[Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "Yes"): a
DEBUG: {
  "userName": "2694"
}

**Comment by PetriAsi** [comment]
Thanks for reporting this.
I'll look this closer when I'm back on my laptop. Trace shows username writen also as userName,. So this could be parameter case sensitivity issue,but can't confirm it just now.

**Comment by PetriAsi** [comment]
Yep, it was  case sensitivity issue, already fixed in develop. I will release new version in few minutes.

**Comment by PetriAsi** [comment]
Fix is pushed to  master, should be in powershell gallery soon.
