### ISSUE TITLE
ApiKey SecureString Error

### ISSUE THREAD

**Issue by RussellLeVasseur** [snazy2000/SnipeitPS#222]
## Context
Won't connect to SnipeITPS with new Connect-SnipeitPS. 

## Your Environment

* SnipitPS Module version used:  1.10.187
* Operating System and PowerShell version: Windows 11, Powershell 5.1
* Snipe It version: Version v5.1.8 - build 6257

## Expected Behavior
Connect to SnipeIT

## Current Behavior
Throws error when i pass the token as plain text string the same way I have always done. 
![image](https://user-images.githubusercontent.com/58618324/132020526-6833d571-bbb6-47f0-8404-255d7c840a83.png)

As I read it, we should still be able to pass a string to -apiKey?

**Comment by PetriAsi** [comment]
Yes. -apiKey is still there

**Comment by RussellLeVasseur** [comment]
> 
> 
> Yes. -apiKey is still there

but it keeps throwing this error now

**Comment by chillinglucifer** [comment]
I am also receiving this error. Tried adding the -force command in Connect-SnipeitPS but it doesn't work either.

**Comment by PetriAsi** [comment]
@chillinglucifer this is fixed with new release. I closed this issue  too quickly.
