### ISSUE TITLE
-apiKey Failing when using Connect-SnipeitPS

### ISSUE THREAD

**Issue by RussellLeVasseur** [snazy2000/SnipeitPS#223]
My previous issue was closed, but this is a very big breaking error....

## Context
Won't connect to SnipeITPS with new Connect-SnipeitPS. When I revert back to 1.9.183 and go back to Set-SnipeitInfo, everything works again.

## Your Environment

* SnipitPS Module version used:  1.10.187
* Operating System and PowerShell version: Windows 11, Powershell 5.1
* Snipe It version: Version v5.1.8 - build 6257

## Expected Behavior
Connect to SnipeIT using a token string.
![image](https://user-images.githubusercontent.com/58618324/132025938-82a86b13-a60b-4b66-8ed8-c128f479f29c.png)

## Current Behavior
Throws error when i pass the token as a string the same way I/we have always done. 
![image](https://user-images.githubusercontent.com/58618324/132021000-85e4557e-07df-4a6e-9985-b6a5476e3b3d.png)

**Comment by PetriAsi** [comment]
Sorry if I closed last one too fast. I'm checking this right now.

**Comment by PetriAsi** [comment]
Sorry. I missed to test -apiKey with powershell 5.1. Powershell core 7.1 was converting plaintext to secure.srting just fine. I'll add -force parameter that should fix this.

**Comment by PetriAsi** [comment]
Well , this embarrassing bug is now fixed. Will release fix in few minutes.

**Comment by PetriAsi** [comment]
@RussellLeVasseur I just published fix. It should be available at ps gallery in couple of minutes.

**Comment by PetriAsi** [comment]
Please confirm fix and I close this later.

**Comment by RussellLeVasseur** [comment]
> @RussellLeVasseur I just published fix. It should be available at ps gallery in couple of minutes.

Thank you! I'll test on Tuesday after holiday weekend. I trust you've got it and closing now.
