### ISSUE TITLE
Get-SnipeitFieldset

### ISSUE THREAD

**Issue by noxare** [snazy2000/SnipeitPS#227]
## Context

Dear Developer,

when i try to use Get-SnipeitFieldset i get an error.

The Description is German, i hope that this is not an Problem.

Thank you

Oliver

## Your Environment

* SnipitPS Module version used: 1.10.189
* Operating System and PowerShell version: Win10
* Snipe It version: V.5.1.8

## Current Behavior

bagin : Die Benennung "bagin" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, 
oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.10.189\Public\Get-SnipeitFieldset.ps1:34 Zeichen:5
+     bagin {
+     ~~~~~
    + CategoryInfo          : ObjectNotFound: (bagin:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Get-Process : Der Parameter "Name" kann nicht ausgewertet werden, da dessen Argument als Skriptblock angegeben wurde und keine Eingabe vorhanden ist. Ein Skriptblock kann nicht ohne Eingabe 
ausgewertet werden.
In C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.10.189\Public\Get-SnipeitFieldset.ps1:58 Zeichen:13
+     process {
+             ~
    + CategoryInfo          : MetadataError: (:) [Get-Process], ParameterBindingException
    + FullyQualifiedErrorId : ScriptBlockArgumentNoInput,Microsoft.PowerShell.Commands.GetProcessCommand
 
**### end** : Die Benennung "end" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob 
der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.10.189\Public\Get-SnipeitFieldset.ps1:63 Zeichen:5
+     end {
+     ~~~
    + CategoryInfo          : ObjectNotFound: (end:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

## Steps to Reproduce (for bugs)

1. Using Get-Snipeitfieldset and not returns an list
2.
3.
4.

**Comment by PetriAsi** [comment]
Thanks for reporting this, this seem to be classic typo. Will fix this soon.
