### ISSUE TITLE
Get-SnipeitLicense

### ISSUE THREAD

**Issue by noxare** [snazy2000/SnipeitPS#230]
Dear Developer,

Get-SnipeitLicense doing the same Error as the already reportet Get-Fieldset Error.
Thx 4 ur fast replys and hard work on this Module.

## Your Environment

* SnipitPS Module version used:
* Operating System and PowerShell version:
* Snipe It version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by PetriAsi** [comment]
Thanks again , already fixed it same time with get-fieldset. Please update your installed module :)
