### ISSUE TITLE
Set-SnipeitLicense

### ISSUE THREAD

**Issue by noxare** [snazy2000/SnipeitPS#232]
## Context

Dear Developer,

when I use Set-Snipeitlicense the command -notes wouldnt work: 

Set-SnipeitLicenseSeat: A parameter cannot be found that matches parameter name 'notes'.

With "Tab" it suggest note but does not set the note.

And know a Question why i use the note field and found this issue: 

Is it a Problem of the Snipeit-Database that there is no connection between the checked out License and the asset
or could it be an additional function that i should ask u too build?
In my example i read the OS license from Bios but sometimes there is no key. I do the trick with an empty key and use the UUID from the PC in the notes field.
This is an Possibility but it makes check in and check out of Licenses rly annoying. In the LicenseSeat function i couldnt do a search for the assigned asset and have to know the id.

Is there a solution for that, what i didnt see?

Thanks for your hard work.

## Your Environment

* SnipitPS Module version used:
* Operating System and PowerShell version:
* Snipe It version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by yaroz** [comment]
@noxare What version of snipeit are you on?  I'm running 5.1.8 here, and it's working fine.

**Comment by yaroz** [comment]
If you check your activity log, does it show the notes on the right side?  I thin that's all the note switch is for when assigning licenses, as there is no "notes" field for the license seat.  I know there has been talk about adding different fields to licenses.  One of my biggest pet peaves is that we have one software with 30 different seats that all expire at different times.  :(  So we have to have 30 different licenses set up in Snipeit.  Each with it's own expiration date.

With that, do you have one license per key?

**Comment by PetriAsi** [comment]
there no notess property just note for acivity log. bt
@noxare  after you assign license to user or asset it should show up like: 
(Dont let all 3's confuse you, it was just coincidence that user id , location id and license id's were same)
```powerhell
id                : 7
license_id        : 3
assigned_user     : @{id=3; name=Petri Asikainen; department=}
assigned_asset    :
location          : @{id=3; name=Ulvila, }
reassignable      : True
user_can_checkout : False
name              : Seat 5
available_actions : @{checkout=True; checkin=True; clone=True; update=True; delete=True}
```
so find out what seats is assigned to "Petri Asikainen" (id 3)

```powershell
Get-SnipeitLicenseSeat -id 3 | where-object { $_.assigned_user.id -eq 3}

#and check in all licenses from specific user
Get-SnipeitLicenseSeat -id 3 | where-object { $_.assigned_user.id -eq 3} | ForEach-Object { Set-SnipeitLicenseSeat -id 3 -seat_id $_.id -assigned_to $null} 
```
