### ISSUE TITLE
Set-SnipeitLicenseSeat

### ISSUE THREAD

**Issue by yaroz** [snazy2000/SnipeitPS#233]
Should the -id parameter be changed to license_id?  Took me a few minutes to figure out that this was looking for the license id, instead of the id of the license seat.

**Comment by PetriAsi** [comment]
Currently SnipeitPS is trying to follow snipe it api and parameter names from there, when ever possible. 
Second reason is that most of get commands will return items with "id" attibute. So keeping id fo set-command is constant and also allow doing things like:
```powershell
get-SnipeitLicence | where-object { [some fancy filter ] | Set-SnipeitLicenseSeat 
```
and so on.
