### ISSUE TITLE
Error Using Set-SnipeitAsset

### ISSUE THREAD

**Issue by axisfx24** [snazy2000/SnipeitPS#237]
## Context
Trying to update an asset, I get a failing error.

DEBUG: Invoke-SnipeitMethod url: https://irvdcsnipeit
DEBUG: {
  "order_number": "4"
}
VERBOSE: [Invoke-SnipeitMethod] Invoking method Patch to URI
DEBUG: [Invoke-SnipeitMethod] Invoke-WebRequest with:
Name                           Value
----                           -----
ErrorAction                    SilentlyContinue
Headers                        {Authorization, Accept, Content-Type}
Method                         Patch
Body                           {123, 13, 10, 32…}
UseBasicParsing                True
Uri                            https://irvdcsnipeit/api/v1/hardware/60

VERBOSE: PATCH https://irvdcsnipeit/api/v1/hardware/60 with 27-byte payload
VERBOSE: received 1293-byte response of content type text/html
VERBOSE: [Invoke-SnipeitMethod] Failed to get an answer from the server
DEBUG: [Invoke-SnipeitMethod] Executed WebRequest. Access StatusCode: 405, ReasonPhrase: 'Method Not Allowed', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Microsoft-IIS/10.0
  Date: Fri, 22 Oct 2021 22:11:17 GMT
  Allow: GET
  Allow: HEAD
  Allow: OPTIONS
  Allow: TRACE
  Content-Type: text/html
  Content-Length: 1293
} to see details
VERBOSE: [Invoke-SnipeitMethod] Status code: MethodNotAllowed
VERBOSE: StatusCode: 405, ReasonPhrase: 'Method Not Allowed', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Microsoft-IIS/10.0
  Date: Fri, 22 Oct 2021 22:11:17 GMT
  Allow: GET
  Allow: HEAD
  Allow: OPTIONS
  Allow: TRACE
  Content-Type: text/html
  Content-Length: 1293
}
VERBOSE: Status:
VERBOSE: Messages:
VERBOSE: [Invoke-SnipeitMethod] Function ended

## Your Environment

* SnipitPS Module version used: 1.10.207
* Operating System and PowerShell version: Win10, PS 7.1.5
* Snipe It version: 5.3.0

## Steps to Reproduce (for bugs)
Choosing any field to update, using pipe data from Get-SnipeitAsset, using a variable or static ID, fails with the error above.

Ex: Set-SnipeitAsset -id '60' -order_number '4'

**Comment by PetriAsi** [comment]
Nice that you fixed it. Have fun.
