### ISSUE TITLE
Please use Connect-SnipeitPS to setup connection before any other commands.

### ISSUE THREAD

**Issue by RussellLeVasseur** [snazy2000/SnipeitPS#238]
## Context
Updated from Set-SnipeItInfo to Connect-SnipeitPS. Seeing `Please use Connect-SnipeitPS to setup connection before any other commands.` errors now. I am delaring the Connect-SnipeitPS towards the beginning of the script just like before. 

## Your Environment
* SnipitPS Module version used: 1.10.207
* Operating System and PowerShell version: Windows 11, Powershell 5.1.22000.65
* Snipe It version: v5.3.0

## Expected Behavior
Declare Connect-SnipeitPS at the beginning of a script and run SnipeitPS commands throughout the rest of the script without re-declaration or re-connection.

## Current Behavior
Throwing an error at each SnipeitPS command. 

## Possible Solution
Is this behavior how it should be with the new command? I would prefer it to be the old way of declaring the info/connection once and then running the script off of that. 

![image](https://user-images.githubusercontent.com/58618324/138765907-4545c561-9a44-4279-a17a-db94fa59dc51.png)

**Comment by PetriAsi** [comment]
Closing this as no response from issue creator
