### ISSUE TITLE
Creating asset's

### ISSUE THREAD

**Issue by colins1019** [snazy2000/SnipeitPS#245]
## Context

Trying to automate the creation of assets

## Your Environment

* SnipitPS Module version used: 
* Current version
* Operating System and PowerShell version: 
* 10, current version
* Snipe It version:  
v5.2.0 build 6339 (g14a8baeca)
## Expected Behavior

To create an asset with make, model, serial, manufacturer and status

## Current Behavior

Script fails at creating the asset.

Sorry I am not sure how to do that.
## Steps to Reproduce (for bugs)

![2021-10-29 19_13_39-Window](https://user-images.githubusercontent.com/90286793/139510562-6edb8ed9-6af3-40a4-ac78-8fb7c7dad571.png)
[snipeitpstest.zip](https://github.com/snazy2000/SnipeitPS/files/7445350/snipeitpstest.zip)

**Comment by PetriAsi** [comment]
Lets see, couple of questions here

First,  is asset with tag "IT008003" already in snipe?
Is snipe setup to  automatically generate new asset tags  (see settings -> asset tags on snipe) ?

Could you please use -verbose and -debug switch with  New-SnipeitAsset and provide output here , thank you.
