### ISSUE TITLE
Reset-SnipeitAssetOwner -notes parameter not working

### ISSUE THREAD

**Issue by TurboSmoothie** [snazy2000/SnipeitPS#246]
## Context

Assets check in successfully, but notes are not displayed.

## Your Environment

* SnipeitPS Module version used: 1.10.211
* Operating System and PowerShell version: Windows 10, 5.1.19041.1320
* Snipe It version: v4.6.13** build 3985

## Steps to Reproduce (for bugs)

Only two parameters used, -id and -notes (Reset-SnipeitAssetOwner -id 1 -notes 'example notes')
Using -note instead of -notes has no affect. Assets are still checked in successfully (without notes)

**Comment by PetriAsi** [comment]
It's notes parameter that should be note like in [snipe it api docs](https://snipe-it.readme.io/reference/hardware-checkin)

**Comment by PetriAsi** [comment]
This is fixed in master now. Powershell gallery should update in few minutes.
