### ISSUE TITLE
Can't connect via PowerShell

### ISSUE THREAD

**Issue by Oddalmighty** [snazy2000/SnipeitPS#249]
I'm trying to use the command "Connect-SnipeitPS" in PowerShell. However, I have tried everything and it gives me an error. I enter my Snipe-IT site URL and the app key I created in Snipe-IT. What am I missing?

**Comment by TurboSmoothie** [comment]
Are you including the '-url' and '-apikey'?

Example:
Connect-SnipeitPS -url 'your url' -apiKey

What is the error?

**Comment by Oddalmighty** [comment]
I'll type in "connect-snipeitps" and it will ask me for both the url and the app key. I enter them when prompted and get this error:
"Cannot verify connection to snipe it. For the start try to check url and provided apikey or credential parameters at "file path".

**Comment by PetriAsi** [comment]
What you are missing?  :) First if you post your Command with -Verbose -Debug we all get more information what could be wrong. So try: 
```powershell
Connect-SnipeItPS -Url [your url] -apikey [your apikey] -Verbose -Debug"
```
and post you logs here (after cleaned your secrets from output).

But as plain guess, self created certificates are most common to cause trouble.

You can test if powershell can  connect your site by running something like.
```powershell
Invoke-WebRequest [your-site-url]
```
It should return Statuscode 200 and something like:
```pre
StatusCode        : 200                                                                                                                                       StatusDescription : OK                                                                                                                                        Content           :  <!DOCTYPE html>                                                                                                                          
                    <html lang="en-US">
                        <head>
                            <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
                            <meta name="viewport" content="width=device-width, initial-scale=1.0, user-sc…
RawContent        : HTTP/1.1 200 OK
                    Cache-Control: no-store, no-cache

```

**Comment by MalteKiefer** [comment]
I have the same problem:

```powershell
PS C:\Users\administrator> Invoke-WebRequest https://itc.intellytec.net
Invoke-WebRequest : Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..
In Zeile:1 Zeichen:1
+ Invoke-WebRequest https://itc.intellytec.net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

But my site uses the latest Let's Encrypt Certificate:

![image](https://user-images.githubusercontent.com/59220985/143670047-eb4eec22-46f0-4251-ae85-1b00749f8434.png)

**Comment by PetriAsi** [comment]
Have you tried to force powershell to use tls1. 2 by running 

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Before invoke-webrequest. If it help find out how to make it default for your system.

**Comment by MalteKiefer** [comment]
LOL my server only allow TLSv1.2.
That could be really helpful, thanks


﻿

Have you tried to force powershell to use tls1. 2 by running

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Before invoke-webrequest. If it help find out how to make it default for your system.

**Comment by Oddalmighty** [comment]
That actually makes perfect sense. We do have a self-signed certificate in place on our site. Is there a way around that?

**Comment by PetriAsi** [comment]
Yes, try following to [skip certificate check](https://til.intrepidintegration.com/powershell/ssl-cert-bypass)

**Comment by PetriAsi** [comment]
@Oddalmighty  I'm closing this, hope you got your issue resolved. Feel free to reopen issue if needed.

**Comment by Oddalmighty** [comment]
Oops! Sorry for not updating. I figured it out. There was an obscure firewall setting that was blocking the connection. Thank you for the help! :)

**Comment by PetriAsi** [comment]
Great that you got that resolved and posting here. :)
