### ISSUE TITLE
New-AssetMaintenance the start date field is required

### ISSUE THREAD

**Issue by macaddict89** [snazy2000/SnipeitPS#25]
Believe this is related to parameter being $startdate and $values[start_date] in New-AssetMaintenance, but wasn't sure which one needs to be changed to ensure that Invoke_SnipeitMethod worked correctly.
`New-AssetMaintenance -asset_id $assetID -supplier_id $supplierID -asset_maintenance_type "Maintenance" -title $maintTitle -start_date $Today -completionDate $Today`

```powershell
Invoke-SnipeitMethod : 
start_date                         
----------                         
{The start date field is required.}
```
SnipeIT v4.6.15 - build 4011 (master)
SnipeitPS 1.0.48

**Comment by snazy2000** [comment]
Opps my bad, will get that fixed shortly!
