### ISSUE TITLE
Set-SnipeITAsset Feature Update

### ISSUE THREAD

**Issue by Christopheric1** [snazy2000/SnipeitPS#251]
I was wondering if it would be possible to add "eol" to the current options in Set-SnipeITAsset. The reason I would like to use this is I am trying to set the dates via a script, but I have them in a separate asset inventory system with the correct dates and want to overwrite them in Snipe-IT with the correct dates from the other one. 

Something like this would be great:
Set-SnipeITAsset -id $computer.id -eol $replacementdate

Thanks!

**Comment by PetriAsi** [comment]
That could be handy, but is it that eol date is derived from eol months for specific model? So you cannot update it directly?
II cannot see even eol field on my assets. Although we don't use eol monts on models either. We have specified custom field for this purpose we save our lease ending day.

As always you can try to update any asset field with :
-customfields =  @{ "fieldname" = "fieldvalue"}

Let us know how it goes.

**Comment by Christopheric1** [comment]
I ended up approaching it at a different angle and it was thanks to you sparking my memory. Since the EOL is set on Model, the purchase_date is what drives the EOL. I just went and updated the purchase dates to reflect my other system and everything is good now! 

I just used the: Set-SnipeITAsset -id $snipeitasset.id -purchase_date $purchasedate

Thanks for the help!
