### ISSUE TITLE
Using v1.10.222 with Snipe-IT v6.0.1 

### ISSUE THREAD

**Issue by Lionsit** [snazy2000/SnipeitPS#270]
Hello, first of all thank you for your awesome PowerShell Module, and sorry for generating an issue for a question.

I'm currently running Snipe-IT v5.4.4 with v1.10.222 of your PowerShell Module, and it works perfect. Is v1.10.222 of your PowerShell Module already compatible with Snipe-IT v.6.0.1 so i can upgrade my Server? Thank you and Best Regards.

**Comment by PetriAsi** [comment]
Theres no major changes in [Snipe IT API](https://snipe-it.readme.io/reference/api-overview), so SnipeitPS should be very compatible with v.6.
