### ISSUE TITLE
Connect-SnipeitPS is erroring out

### ISSUE THREAD

**Issue by VicYukonU** [snazy2000/SnipeitPS#284]
## Context

Nope Sorry I'll close this issue.  It was on our end.  The developers here changed the cert associated with snipeit and then felt it was a good idea to associate the GPU that pushes it out with a TEST-OU... snipe is a production system... go figure.  Once I put my machine into the correct OU and verified the cert authority was in my cert authority list... It all works now

My humble appologies for bothering you good sir!

VIC
=+=

The connection to our SNIPEIT no longer succeeds.  Using the Connect-SnipeitPS command.  It was working on Saturday (3 days ago) but now is not working.  I can login via web page, I can ping it, I have admin priv in snipeit and the apikey I generated is not expired and is generated under my snipeit account.  In some of the other api's I use from this powershell script there is a parameter to ignore cert errors on the connection.  We are using a self signed cert and it is not in my windows cert store.  Could that be the issue?
## Your Environment

* SnipitPS Module version used:
* Operating System and PowerShell version:
* Snipe It version:
Windows 10 Education 
Powershell v7.x
Tried doing update module -force (which succeeded but didn't change the error behavior)
My box is windows 10 education (pro) OS Build 19044.1889
SNIPEIT Version..  Version v6.0.9 - build 8515 (master)
## Expected Behavior

Previously (before the long weekend) when I issued the Connect-SnipeitPS command with the -url and -apikey parameters, the connection worked just fine.  It is now throwing an error in the Connect-Snipeitps.ps1 script at line 146:13
## Current Behavior

Now when I execute the command Connect-Snipeitps using the -url and -apikey (and -verbose) parameters I get the following...
$theconn = Connect-SnipeitPS -url $myurl -apikey $mytoken -verbose
VERBOSE: Testing connection to http://our snipe server url.
VERBOSE: [ConvertTo-GetParameter] Making HTTP get parameter string out of a hashtable
VERBOSE: [Invoke-SnipeitMethod] Invoking method Get to URI 
VERBOSE: GET with 0-byte payload
VERBOSE: [Invoke-SnipeitMethod] Failed to get an answer from the server
VERBOSE: [Invoke-SnipeitMethod] No Web result object was returned from. This is unusual!
VERBOSE: [Invoke-SnipeitMethod] Function ended
Exception: C:\Users\vhopkinslecheminanta\Documents\PowerShell\Modules\SnipeitPS\1.10.227\Public\Connect-SnipeitPS.ps1:146:13
Line |
 146 |              throw "Cannot verify connection to snipe it. For the star …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot verify connection to snipe it. For the start try to check url and provided apikey or credential parameters
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

I realize the issue might be on our end, I run the script in an elevated powershell session and connect to the web page for snipeit in a regular user not elevated session...  If there is any diagnostic I should run/check beyond what I have done I appologize for not thinking of it.  I'll keep trying to figure it out on our end also...  Many thanks for your awesome module!

VIC
=+=

**Comment by PetriAsi** [comment]
Thanks to updating this issue. I'm glad that you resolved this.
