### ISSUE TITLE
Namespacing cmdlets

### ISSUE THREAD

**Issue by wrbeaudo** [snazy2000/SnipeitPS#30]
Any issue with renaming all of the cmdlets to verb-SnipeITnoun?  That will handle the conflicts and follow MS best practices.  If not, I am fine putting in a pull request for that.

**Comment by snazy2000** [comment]
You could just import the module using

Import-Module Snipeitps -Prefix snipeit. 

I believe :)

**Comment by wrbeaudo** [comment]
True. But after needing a Set-Location and forgetting to prefix it once, the amount of time to cleanup my cron job was almost as long as it would have taken to update the code.  Up to you.

**Comment by trch15** [comment]
Please fix this

**Comment by PetriAsi** [comment]
As Get-Location is already prefixed with Snipeit, it would make sense to prefix all other functions too.
Maybe also do some kind of compatibility function to set alias from new function names to old ones to help with transition.

**Comment by PetriAsi** [comment]
Renaming  current functions with "SnipeIt", adding aliases to keep backward compatibility and exporting them with AliasesToExport would allow to this without any interruptions current scripts.

**Comment by PetriAsi** [comment]
Maybe there's need to notify users about depreciated functions and give info to use new prefixed ones.

**Comment by PetriAsi** [comment]
Now we have following message about new prefix and aliases:
```powershell
VERBOSE: Setting compatibility aliases..
VERBOSE: All aliases are deprediated.
VERBOSE: Get-Asset -> Get-SnipeItAsset
VERBOSE: Get-Manufacturer -> Get-SnipeItManufacturer
VERBOSE: Get-CustomField -> Get-SnipeItCustomField
VERBOSE: Set-AssetOwner -> Set-SnipeItAssetOwner
VERBOSE: Get-Status -> Get-SnipeItStatus
VERBOSE: Get-Model -> Get-SnipeItModel
VERBOSE: Get-Department -> Get-SnipeItDepartment
VERBOSE: Set-Model -> Set-SnipeItModel
VERBOSE: Set-User -> Set-SnipeItUser
VERBOSE: Get-Fieldset -> Get-SnipeItFieldset
VERBOSE: New-Accessory -> New-SnipeItAccessory
VERBOSE: New-Component -> New-SnipeItComponent
VERBOSE: New-Location -> New-SnipeItLocation
VERBOSE: New-CustomField -> New-SnipeItCustomField
VERBOSE: New-Category -> New-SnipeItCategory
VERBOSE: Get-Category -> Get-SnipeItCategory
VERBOSE: New-License -> New-SnipeItLicense
VERBOSE: New-Department -> New-SnipeItDepartment
VERBOSE: New-Asset -> New-SnipeItAsset
VERBOSE: Get-User -> Get-SnipeItUser
VERBOSE: Set-Asset -> Set-SnipeItAsset
VERBOSE: Set-Component -> Set-SnipeItComponent
VERBOSE: Set-Info -> Set-SnipeItInfo
VERBOSE: Get-Company -> Get-SnipeItCompany
VERBOSE: Get-AssetMaintenance -> Get-SnipeItAssetMaintenance
VERBOSE: Remove-User -> Remove-SnipeItUser
VERBOSE: New-AssetMaintenance -> New-SnipeItAssetMaintenance
VERBOSE: Get-Component -> Get-SnipeItCompany
VERBOSE: Set-License -> Set-SnipeItLicense
VERBOSE: Remove-Asset -> Remove-SnipeItAsset
VERBOSE: Set-Accessory -> Set-SnipeItAccessory
VERBOSE: New-Manufacturer -> New-SnipeItManufacturer
VERBOSE: New-User -> New-SnipeItUser
VERBOSE: New-Model -> New-SnipeItModel
VERBOSE: Get-Accessory -> Get-SnipeItAccessory
VERBOSE: Get-Supplier -> Get-SnipeItSupplier
VERBOSE: Please start using native 'SnipeIt'-functions instead.
```

**Comment by PetriAsi** [comment]
Would it make sense to test $MyInvocation.InvocationName on every function call and give notification every time if aliased version  of function is used?

**Comment by PetriAsi** [comment]
Added Update-SnipeItAlias helper function that can be use to update exiting script.
Helper function is also mentioned if old aliases version of function is used.
 
```powershell
WARNING: Set-Info is still working, but it has been superceded by Set-SnipeItInfo, please use it instead.
WARNING: To update your scripts you can use Update-SnipeItAlias helper function:
WARNING: "Get-Content [your-script.ps1] | Update-SnipeItAlias | Out-File [new-script-name.ps1]"
```

**Comment by PetriAsi** [comment]
Fixed in v.1.2x
