### ISSUE TITLE
Password Confirmation does not match

### ISSUE THREAD

**Issue by SlenderJam** [snazy2000/SnipeitPS#31]
When attempting to create new users:
`New-User -firstName $Firstname -lastName $Lastname -userName $Username -email $Email -location_id $Location -apiKey $ApiKEY -url $ApiURL -password $Password`

It returns with:
```
`Invoke-SnipeitMethod :
password
--------
{The password confirmation does not match.}
At C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.0.54\Public\New-User.ps1:141 char:19
+         $result = Invoke-SnipeitMethod @Parameters
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-SnipeitMethod`
```

I can't find a passable parameter, or the script isn't passing the password field correctly.

**Comment by snazy2000** [comment]
Looks like need to pass same value into password_confirmation as well, ill see what can do later :)
