### ISSUE TITLE
REQUEST: NEW-ASSET -serial

### ISSUE THREAD

**Issue by SlenderJam** [snazy2000/SnipeitPS#33]
Allow entry of serial numbers when creating assets

**Comment by jonas-westphal-at-banovo** [comment]
This is very important.
Im stuck here too.

**Comment by snazy2000** [comment]
You can do this which is what I currently do in my PS script

The variables with _ in them are custom fields but you can put any field type in there

$CustomValues = @{
    _snipeit_cpu_2 = $CPUInfo.NumberOfCores
    _snipeit_memory_gb_3 = $PhysicalMemory
    _snipeit_os_5 = $OSInfo.Caption
    serial = $bios.SerialNumber
    warranty_months = $warrantyMonths
}
$asset = New-Asset -status_id 2 `
                    -model_id $model.id `
                    -name $machine.Name `
                    -customfields $CustomValues

**Comment by jonas-westphal-at-banovo** [comment]
I can confirm this works. This should be added to the readme.
