### ISSUE TITLE
Token?

### ISSUE THREAD

**Issue by kochsts** [snazy2000/SnipeitPS#34]
Hi,

I like your Project. It looks very nice. 
I want to use it but I cant find the right tokenkey.

I tried my application token of snipeits .env. Furthermore I tried creating an snipe key by using following command: php artisan passport:client

Can you please help me.

Thanks

**Comment by snazy2000** [comment]
Take a look at the documentation

https://snipe-it.readme.io/reference#generating-api-tokens

That should help you out :)

**Comment by kochsts** [comment]
![image](https://user-images.githubusercontent.com/49901614/59433036-f1319b80-8de8-11e9-940f-228406eace62.png)

I try it like this by using my personal key. Is this correct?

Thanks for your fast answer

**Comment by snazy2000** [comment]
Yes that looks correct
