### ISSUE TITLE
Get-User search results include all users that have user as a manager as well

### ISSUE THREAD

**Issue by fletch8527** [snazy2000/SnipeitPS#35]
When I run `Get-User -search msmith` I would expect the result to be msmith's details from Snipe. What I am actually getting is that user's details as well as all other users' details that also have msmith as a manager. Is there a way to limit the search to just a particular field in Snipe's user details? 
Example: `Get-User -search msmith -searchfield username`

**Comment by PetriAsi** [comment]
Fixed in develop, now you can use -username and -email parameters to get specific user
