### ISSUE TITLE
New-Model works, New-Asset does not

### ISSUE THREAD

**Issue by DerKiLLa** [snazy2000/SnipeitPS#37]
Creating a new model works:

**New-Model -name "Latitude E6540" -manufacturer_id 1 -category_id 2 -fieldset_id 0**

category_id     : 2
fieldset_id     : 
name            : Latitude E6540
manufacturer_id : 1
updated_at      : 2019-11-20 12:10:18
created_at      : 2019-11-20 12:10:18
id              : 5

But when i try to add a new asset, nothing happens:

**New-Asset -status_id 2 -model_id 5 -name "DE001LA0002"**

No error, no message.

**Comment by DerKiLLa** [comment]
Okay, with tag it works ... but -tag is not required?

**New-Asset -status_id 2 -model_id 5 -name "DE001LA0002" -tag "DE001LA0002"**

**Comment by snazy2000** [comment]
Do you have auto-increment setup against your assets?

**Comment by DerKiLLa** [comment]
Thanks, no. That was the problem :)

Solved!
