### ISSUE TITLE
New-User without success?

### ISSUE THREAD

**Issue by DerKiLLa** [snazy2000/SnipeitPS#38]
` New-User -firstName "Peter" -userName "Test" -password "Test123454566" -LastName "Meier"`

Does not return an error or anything, but does not work. Have the same problem, when i try to do it in C#, so i think this is a change from Snipeit?

```
PS C:\Users\014nr9999> New-User
Cmdlet New-User an der Befehlspipelineposition 1
Geben Sie Werte für die folgenden Parameter an:
firstName: A
lastName: B
userName: D
```

no success ...

**Comment by DerKiLLa** [comment]
More information: New-User needs an password_confirmation field in the Snipeit API. I think, thats the error ...

**Comment by snazy2000** [comment]
Its being set if ldap is not set to true

Can you try force setting ldap_user to $false and see if that makes any difference?

if ($ldap_user -eq $false) {
        $ldap = @{
            password    = $password
            password_confirmation = $password
            ldap_import = 0
        }
    }

**Comment by DerKiLLa** [comment]
Still no success with

`New-User -firstName "Peter" -userName "Test" -LastName "Meier" -ldap_user 0`

**Comment by PetriAsi** [comment]
Current develop branch have no this this issue. It will roll out to powershell gallery soon. Please reopen new issue if needed.
