### ISSUE TITLE
Get-User | empty results after few searches in loop

### ISSUE THREAD

**Issue by hiimmazl** [snazy2000/SnipeitPS#39]
Hi,

trying to use the "Get-User" command for a "foreach loop". 

It successfully searches for the first 120 users, but then just returns blank. 

Also if I search for all users with -Limit "9999" it only returns the maximum amount of "500" users.

Any ideas on this topic?

Thanks in advance!

**Comment by snazy2000** [comment]
This is prob a limit in the API itself, ill take look at documentation later and get back to you


Sent from Yahoo Mail for iPhone


On Tuesday, November 26, 2019, 10:29 am, hiimmazl <notifications@github.com> wrote:


Hi,

trying to use the "Get-User" command for a "foreach loop".

It successfully searches for the first 120 users, but then just returns blank.

Also if I search for all users with -Limit "9999" it only returns the maximum amount of "500" users.

Any ideas on this topic?

Thanks in advance!
