### ISSUE TITLE
[Request] New-User | Add "-activated" parameter

### ISSUE THREAD

**Issue by hiimmazl** [snazy2000/SnipeitPS#40]
Hi,

would like to request to add the parameter "-activated" to the New-User command.

Right now it is hardcoded into the command with the value "1". 

Greetings,

hiimmazl

**Comment by PetriAsi** [comment]
This is fixed in develop

**Comment by PetriAsi** [comment]
Fixed in version v1.1.x, closing this now. Reopen if needed.
