### ISSUE TITLE
Raise Limit to reasonable count

### ISSUE THREAD

**Issue by jonas-westphal-at-banovo** [snazy2000/SnipeitPS#43]
Hey,
as I am writing i found out that parts of my script did not work because of this issue.

This shouldn't be 50 its way to low.

Two approaches: Make it default to query all **or** change it to a reasonable number like 2000.

**Comment by snazy2000** [comment]
You can override the limit. Ive looked at the default in snipe it and its 500, so i will look to change to that

**Comment by PetriAsi** [comment]
-all switch is pushed to develop branch. It will recursively query all items from snipe.
