### ISSUE TITLE
Set-Asset Doesn't Work

### ISSUE THREAD

**Issue by shharp** [snazy2000/SnipeitPS#45]
Set-Asset was having an issue applying any changes.  I've added the corrected code that worked for me.

`<#
    .SYNOPSIS
    Update a Asset in the Snipe-it asset system

    .DESCRIPTION
    Long description

    .PARAMETER id
    ID of the Asset

    .PARAMETER Name
    Name of the Asset

    .PARAMETER Status_id
    Status ID of the asset, this can be got using Get-Status

    .PARAMETER Model_id
    Model ID of the asset, this can be got using Get-Model

    .PARAMETER url
    URL of Snipeit system, can be set using Set-Info command

    .PARAMETER apiKey
    Users API Key for Snipeit, can be set using Set-Info command

    .PARAMETER customfields
    Hastable of custom fields and extra fields that need passing through to Snipeit

    .EXAMPLE
    Set-Asset -id 1 -status_id 1 -model_id 1 -name "Machine1"

    .EXAMPLE
    Set-Asset -id 1 -status_id 1 -model_id 1 -name "Machine1" -CustomValues = @{ "_snipeit_os_5 = "Windows 10 Pro" }
#>

function Set-Asset()
{
    [CmdletBinding(
        SupportsShouldProcess = $true,
        ConfirmImpact = "Medium"
    )]

    Param(
        [parameter(mandatory = $true)]
        [int]$id,

        [string]$Name,

        [int]$Status_id,

        [int]$Model_id,

        [parameter(mandatory = $true)]
        [string]$url,

        [parameter(mandatory = $true)]
        [string]$apiKey,

        [hashtable] $customfields
    )

    $Values = @{
        "name"      = $Name
        "status_id" = $status_id
        "model_id"  = $model_id
		"id"        = $id
    }

    if ($customfields)
    {
        $Values += $customfields
    }

    $Body = $Values | ConvertTo-Json;
	write-host $Body
    $Parameters = @{
        Uri    = "$url/api/v1/hardware/$id"
        Method = 'PATCH'
        Body   = $Body
        Token  = $apiKey
    }

    If ($PSCmdlet.ShouldProcess("ShouldProcess?"))
    {
        $result = Invoke-SnipeitMethod @Parameters
    }

    $result
}
`

**Comment by snazy2000** [comment]
Please make a pull request

**Comment by PetriAsi** [comment]
This seem be related to #57 , PUT and PATCH are updating items differently. Closing this issue here and left #57 open.
