### ISSUE TITLE
all commands are not working

### ISSUE THREAD

**Issue by thebest07111** [snazy2000/SnipeitPS#55]
I have for example this powershell script:

$apikey = "apikey here"
@url = "https://snipeit.edsn.local/"
 
New-User -firstName "klaas" -lastName "Chris" -userName "kchris" -password "whatever" -ldap_user 0 -jobTitle "manager" -email "test@test.com" -url $url -apiKey $apikey

When I run the command i am not getting any feedback but also not the user

**Comment by thebest07111** [comment]
I mean $url instead of @url

**Comment by snazy2000** [comment]
Does Get-Asset work?

**Comment by thebest07111** [comment]
yes that does seem to work

**Comment by thebest07111** [comment]
It seems that when I do https with a self signed certificate it doesnt work.

**Comment by dilpatel45** [comment]
@thebest07111 I had that issue aswell. This is what I added in my script to allow self signed certificates

```
if (-not("dummy" -as [type])) {
add-type -TypeDefinition @"
using System;
using System.Net;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;

public static class Dummy {
    public static bool ReturnTrue(object sender,
        X509Certificate certificate,
        X509Chain chain,
        SslPolicyErrors sslPolicyErrors) { return true; }
    public static RemoteCertificateValidationCallback GetDelegate() {
        return new RemoteCertificateValidationCallback(Dummy.ReturnTrue);
    }
}
"@
}

[System.Net.ServicePointManager]::ServerCertificateValidationCallback = [dummy]::GetDelegate()
```

**Comment by PetriAsi** [comment]
Other workaround could be importing servers  self signed certificate to trusted certificate store on local computer.

As this was issue with self signed certificates, I'll close this now. Please reopen new issue if needed.
