### ISSUE TITLE
Put vs Patch for Set-Asset

### ISSUE THREAD

**Issue by ambersferrara** [snazy2000/SnipeitPS#57]
I'll work on contributing, but I wanted to mention some behaviors that I've seen when using the Put instead of Patch for set-asset.  I created my own version of set-asset to introduce all the other parameters I needed.  I also created what I called an Update-asset function that uses Patch.

When using Put to change information for an asset the location for that asset no longer reflects the assigned users location, but instead the default rtd location.  Checking the asset back in and back out resolves this, or logging into the site and editing/saving the user (no change required).  

When using Patch instead the location information is retained.  In my case I only added warranty months and purchase date to the attributes so I could automate the Dell warranty import.

I'm going to try to amend the Set-Asset to use Patch instead of Put and add all current parameters for the Patch API to see if that works consistently.

**Comment by PetriAsi** [comment]
What if this get implemented as parameter for Set-Asset.  Parameter could be called like "-RequestType" defaulting to "Put" and allowing to specify "Patch" as option.
This way there no need to duplicate code between to different functions.

**Comment by PetriAsi** [comment]
@ambersferrara 
[Approved Verbs for PowerShell Commands](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.1)

Set :	Replaces data on an existing resource or creates a resource that contains some data. For example, the Set-Date cmdlet changes the system time on the local computer. (The New verb can also be used to create a resource.) This verb is paired with Get.

Update :	Brings a resource up-to-date to maintain its state, accuracy, conformance, or compliance. For example, the Update-FormatData cmdlet updates and adds formatting files to the current PowerShell console.

Edit :	Modifies existing data by adding or removing content.

I would choose verb "Edit" over "Update" if this feature get  implemented as new function.

**Comment by PetriAsi** [comment]
This is now implemented  as -Requesttype parameter for Set-SnipeItAsset function in develop branch . Now you can select between post and patch when needed.

**Comment by PetriAsi** [comment]
Fixed in v1.3
