### ISSUE TITLE
checkin/checkout licenses

### ISSUE THREAD

**Issue by MrMontesa** [snazy2000/SnipeitPS#59]
Hey there,
I'm trying some automation and assign licenses based on an active directory groups. Is there any possibility to checkin/checkout licenses to users using SnipePS? Can I somehow get the users who currently have a seat checked-out? In Snipe web frontend this can be seen on the Seats tab in license view.
Any idea if and how to achieve this? Let me know if you have any questions.
Thanks

**Comment by MrMontesa** [comment]
A bit of research might have revealed that Snipe API is lacking this feature. Found https://github.com/snipe/snipe-it/issues/6695

**Comment by MrMontesa** [comment]
Above mentioned Snipe issue is closed and has been merged to develop branch. Would be awesome to have this feature also available in SnipePS.

**Comment by MrMontesa** [comment]
Hey,
today the license API endpoint has been released to production v5.1.5 using pull request https://github.com/snipe/snipe-it/pull/8058.
Would be awesome to have this also available in SnipitPS now.

**Comment by PetriAsi** [comment]
@MrMontesa  thank's for information. This would be nice to have here also as api is supporting this.
Is anyone interested to make pull request for this ?

**Comment by PetriAsi** [comment]
Pulled to develop

**Comment by PetriAsi** [comment]
Fixed in v.1.2x
