### ISSUE TITLE
Set-Asset with customfield

### ISSUE THREAD

**Issue by MrMontesa** [snazy2000/SnipeitPS#60]
Hey,
I'm trying to update the SnipeIT with some CVS file content and got to the point where I have to update a custom_field.

Docu sais:
```
PS C:\scripts\windows> Get-Command -Module SnipeitPS
...
Function        Set-Asset                                          1.0.57     SnipeitPS
...
Get-Help Set-Asset -Full
...
-------------------------- EXAMPLE 2 --------------------------
    
    PS C:\>Set-Asset -id 1 -status_id 1 -model_id 1 -name "Machine1" -CustomValues = @{ "_snipeit_os_5 = "Windows 10 Pro" }
```
Seems like _-CustomValues_ is outdated as I found _-customfields_ referenced in [another ticket](13).
But I'm somehow not able to create a proper hashtable to push my customfield. 

```
PS C:\scripts\windows> Set-Asset -id 772 -customfields = @{ '_snipeit_accounting_id_8' = '410475' }
Set-Asset : Cannot process argument transformation on parameter 'customfields'. Cannot convert the "=" value of type "System.String" to type "System.Collections.Hashtable".
At line:1 char:33
+ Set-Asset -id 772 -customfields = @{ '_snipeit_accounting_id_8' = '41 ...
+                                 ~
    + CategoryInfo          : InvalidData: (:) [Set-Asset], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-Asset
```
Would be great if someone has some recommendations.
Thanks much

Edit 1:
After removing the = assignment from the hashtable a was able to proceed but failing again, as I have to add model_id & status_id mandatory. Even though the CSV is based on a Snipe Export, this data is quite difficult to compute.

**Comment by yaroz** [comment]
-customfields is correct, but there is no = in between that and the hash.

**Comment by PetriAsi** [comment]
Your -customfields was badly formated @{ "_snipeit_os_5 = "Windows 10 Pro" } should be @{ "_snipeit_os_5" = "Windows 10 Pro" } or @{ _snipeit_os_5 = "Windows 10 Pro" } 

Closing this now
