### ISSUE TITLE
-search parameter does not work on PowerShell Core 7.0

### ISSUE THREAD

**Issue by sheppyh** [snazy2000/SnipeitPS#67]
It just returns all assets to the limit no matter what is entered into -search parameter for all functions including Get-Asset and Get-AssetMaintenance.

Expect it's due to a chance in functionality around this line:

`    $SearchParameter = . Get-ParameterValue`

**Comment by PetriAsi** [comment]
I fixed this on my fork. Something has changed how powershell 7 pass dot sourced enviroment. Variables are passed as before , but $MyInvocation.MyCommand.Parameters is not referensing values from ancestor. So I modified get-parametervalue to require  passing it as parameter.

**Comment by PetriAsi** [comment]
Fixed in develop branch

**Comment by PetriAsi** [comment]
Fixed in version v1.1.x, closing this now. Reopen if needed.
