### ISSUE TITLE
Conflict with existing Get-Location

### ISSUE THREAD

**Issue by DokH** [snazy2000/SnipeitPS#7]
Steven,
 I tried to 'Install-Module SnipeitPS' on a PS 5.1 Windows Server 2012 R2, but PS complained that Get-Location already exists.
 It is already part of this: Microsoft.PowerShell.Management.
 How can I get around this?

**Comment by snazy2000** [comment]
You could do 

import-module SnipeItPS -Prefix SnipeIt  This would make all the commands Get-LocationSnipeIt

I have been thinking of changing the name of this command but not really sure what to call it.

**Comment by snazy2000** [comment]
@DokH did this fix your issue/?

**Comment by DokH** [comment]
I have the issue with the install-module getting the files from the PowerShell gallery.
What should I do to get the files without using PowerShellGet?

**Comment by DokH** [comment]
Thank you. That worked to get SnipeitPS on my server.
Now I need to figure out what it can do for me. I like the idea of feeding the users AD info into Snipe-IT.

**Comment by DokH** [comment]
Solved and tested. Thanks again.

**Comment by fletch8527** [comment]
I know this issue is already closed, but I just wanted to clearify that if you speficy a Prefix when importing SnipeitPS the command would be something like `Get-PREFIXLocation` not `Get-LocationPREFIX`. I just figured I would add this comment incase others are looking here.
