### ISSUE TITLE
Mac Powershell compatibility?

### ISSUE THREAD

**Issue by juosukai** [snazy2000/SnipeitPS#74]
I installed the module on my powershell instance without any issues, but no commands work. I get the same error message regardless of what command I try to run:

`PS /Users/jussi> Get-Asset
ConvertFrom-Json: /Users/jussi/.local/share/powershell/Modules/SnipeitPS/1.0.70/Private/Invoke-SnipeitMethod.ps1:88
Line |
  88 |  …        $response = ConvertFrom-Json -InputObject $webResponse.Content
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected character encountered
     | while parsing value: S. Path '', line 0, position 0.`
    
Is there something wrong with my setup, or is it just incompatibility with the mac powershell environment?

**Comment by nittanygeek** [comment]
What version of PS are you running on the Mac?

**Comment by PetriAsi** [comment]
Use -Verbose switch to more details what could be happening.

Closing this for now as powershell 7 compatibility is in version v1.1.x
