### ISSUE TITLE
-Status parameter does not filter on status

### ISSUE THREAD

**Issue by jeffreytigch** [snazy2000/SnipeitPS#78]
API documentation of Snipe IT states the following: 

> Optionally restrict asset results to one of these status types: RTD, Deployed, Undeployable, Deleted, Archived, Requestable

When I use the -Status parameter to filter "Archived", it does not work. I just get the results as I would get without any filters. When I do an API call without the PS wrapper (`?status=Archived`), it does work as intended, proving the issue does not lie in the instance.

Using the verbose data, I see this being called:

```
VERBOSE: [ConvertTo-GetParameter] Making HTTP get parameter string out of a hashtable
VERBOSE: [Invoke-SnipeitMethod] Invoking method Get to URI http://server/api/v1/hardware?Invocation=System.Management.Automation.InvocationInfo&BoundParameters=System.Management.Automation.PSBoundParametersDictionary&DefaultExcludeParameter=id+url+apiKey+Debug+Verbose
VERBOSE: GET http://server/api/v1/hardware?Invocation=System.Management.Automation.InvocationInfo&BoundParameters=System.Management.Automation.PSBoundParametersDictionary&DefaultExcludeParameter=id+url+apiKey+Debug+Verbose with 0-byte payload
```

Using Powershell Core 7.1.0 on MacOS.

**Comment by jeffreytigch** [comment]
Actually, I saw issue 67 (https://github.com/snazy2000/SnipeitPS/issues/67#issuecomment-769958633) and @PetriAsi seems to have fixed it. @snazy2000, hoping you can merge his pull request.

**Comment by PetriAsi** [comment]
fix  is  pulled to develop branch
