### ISSUE TITLE
Unmaintained Module

### ISSUE THREAD

**Issue by sheppyh** [snazy2000/SnipeitPS#82]
Hello @snazy2000, looks like this module is falling behind on maintenance - could you consider adding me as a contributor/passing the module on for someone else to maintain?

**Comment by PetriAsi** [comment]
@snazy2000  Thank you for you thi great module. Adding contributors or new maintainer for this module is really needed.

**Comment by snazy2000** [comment]
Thank you for offering to help with the module. Ive added you both as contributors for now lets make this module great again!

**Comment by snazy2000** [comment]
Please remember to push to develop branch then create a pull req to master as master will build and test and then publish to gallery

**Comment by PetriAsi** [comment]
Great, thanks! I'll start to merge pull request to develop. May be my own first.
It seem that master and develop are currently out on sync, should we merge master first to develop?

And when we are working with develop make all  changes as  feature branches and merge them first to develop and from there to master?

**Comment by snazy2000** [comment]
I believe they are out of date because i merged something in to master by mistake and then rolled it back.

So may need to merge master over to dev yes. 

I think feature branch to develop works best yeah :)

Thanks

**Comment by PetriAsi** [comment]
Most of pull requests merged fine to to develop.  After second look changes between develop and master were so small, so I hope that develop will merge fine with master.

About version numbers and publishing to gallery.  Should we keep CHANGELOG.md updated with all changes and version numbers, what version numbers shoud we set on SnipeitPS.psd1? Could it work if new version number set only before develop is merged to master?   
 
Merging/pushing to master : Is publishing to gallery automatic or do you (@snazy2000) review changes and version numbers before publishing to gallery is done?

**Comment by PetriAsi** [comment]
I merged head to develop and all other pull requests also, with some additional fixes. Issue list have label "fixed-in-develop" for all open issues that have been fixed. 
 
Develop branch seems to work fine to me. I created issue #88  and hope that you  @sheppyh , @snazy2000  and some others could test develop branch before merging it to master and publishing to powershell gallery.

**Comment by PetriAsi** [comment]
@snazy2000 First sorry for spamming you. 
I have done my homework about github publishing with appveyor. But vould you please confirm following:

Is it that appveyor.yml contains all version related setting. So if I  like to push new minor or major (1.1 ,1.2 or 2.0)  version I'll change line in  appveyor.yml:
```yml
version: 1.0.{build}
```
Push it to development branch first and from there to master. And then master will build and publish to gallery automatically.

**Comment by snazy2000** [comment]
Yes it will handle version numbers itself but if you want to go to v2 then would need to change the yaml yeah

It will build on every push in any branch but will only publish on successful build in master :)

Thanks for all work you have put in
