### ISSUE TITLE
Invalid JSON primitive: .

### ISSUE THREAD

**Issue by lcoppenr** [snazy2000/SnipeitPS#84]
SnipeitPS has been working fine until recently and I keep getting the following error.   I'm hoping I'm just doing something wrong.   I used postman to test the API and it seems to be working fine, it is just the Powershell module that is having the issue.

BTW: I also tried reverting to 1.0.57 and have the same error.

ConvertFrom-Json : Invalid JSON primitive: .
At C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.0.76\Private\Invoke-SnipeitMethod.ps1:88 char:29
+ ...        $response = ConvertFrom-Json -InputObject $webResponse.Content
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by lcoppenr** [comment]
So, I'm guessing my question is silly, I asked it in the wrong place or SnipeITPS is dead.    Let's hope it isn't dead.

**Comment by PetriAsi** [comment]
Project undead, back from dead.  And you question was not silly let's continue with it  :)

@lcoppenr , could you provide more information about you powershell environment and command you tried to  to run?

And if you are can use git , please try develop branch, if it fixed this. There's lots of changes that are waiting to be merged to master and from there powershell gallery.

**Comment by lcoppenr** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/40072517/118402618-8239ce80-b61f-11eb-93bb-80444d768501.png">

If I am correct, running Get-Asset should just list all my assets.   I've tried recreating the APIKey, but like I said it appears to be working with Postman to test the API remotely.

PS version:   5      1      19041  906

I have a script that runs on about 275 systems which updates/creates each computer asset.  So there are a lot of systems with PS versions v3 to v7.  Obviously <v5 doesn't work, but non of the systems are updating currently.

How do I install the development module within Powershell?

BTW: Thank you, thank you, thank you.   Snipe-IT would be almost useless to me without this powershell module or a way to script computer asset updates and creates.

**Comment by PetriAsi** [comment]
I wrote little guide how to [install develop version](https://github.com/snazy2000/SnipeitPS/wiki/How-to-use-develop-version-of-SnipeItPS)
But before test it, please confirm that you are using https with trusted certificate. (postman down not complain by default, but now days powershell security has tightened up)
If it's self signed certificate you are using that could be source  of problem. Look at #55  to find workaround  for self signed certificates.

**Comment by lcoppenr** [comment]
I'm using a Let's Encrypt cert, which works fine from the web interface on a several computers (my management/test devices and several clients).  I'll try the develop version and get back to you thx.

**Comment by lcoppenr** [comment]
FIXED.  You were right, it was a certificate problem on our cloud VM's firewall.    Thank you for your time and thank you for keeping SnipeItPS alive.     BTW: If there was a way to have SnipeItPS spit out an error like "can't connector site" or something that would be very helpful.   Once I saw a JSON error, I felt a bit lost.

**Comment by PetriAsi** [comment]
Great to heard that it fixed! We really need some error handling for webrequests.
Have fun with SnipeitPS!
