### ISSUE TITLE
Old pull request are merged to develop, please test

### ISSUE THREAD

**Issue by PetriAsi** [snazy2000/SnipeitPS#88]
Most of pull requests are in develop branch, please test and report if any issues are found.

**Comment by PetriAsi** [comment]
For those who are new to git I wrote little guide how to [install develop version](https://github.com/snazy2000/SnipeitPS/wiki/How-to-use-develop-version-of-SnipeItPS)

**Comment by PetriAsi** [comment]
Pushed to master. First 1.1 release

**Comment by snazy2000** [comment]
Great Job!

**Comment by PetriAsi** [comment]
Thanks! Thank you for helping with this.
